Infinite Health Shield
0
jgduff1
0 01378EDC 7C050050
0 01378EE0 60000000
0 01378F08 7C050050
0 01378F0C 60000000
0 01379D08 EC116828
0 01379D0C 60000000
0 01379D10 60000000
#
Instant Max Armor + No Waiting Time For Armor Regeneration
0
jgduff1
0 0078102C EC02083A
0 00781000 ED615028
#
Infinite Ammo In Clip
0
jgduff1
0 01382368 913F0000
#
Max + Infinite PA On Gain Or Drop
0
jgduff1
0 005806FC 905E0098
0 00580558 905E0098
#
+9999 Gadgets On Use Gadgets
0
jgduff1
0 013792C0 Z
0 013792C8 ZZ
[Z]380B270D=On;380BFFFF=Off[/Z]
[ZZ]91690000=On;90090000=Off[/ZZ]
/*
Activate after you have a
MedPack.

Only use to increase your
gadgets because it will
freeze the game.

Zooming in with weapons
will freeze the game.
*/
#
No Waiting Time For Using MedPack
0
jgduff1
0 00524788 EC3EF828
#
Max + Infinite Found Items On Buy 2 times
0
jgduff1
0 008A3360 Z
[Z]93A90000=On;93090000=Off[/Z]
/*
Never buy Gadget Items
with this code on.

This freezes the game at
the end of missions.

Only use it to increase
your Found at your House
before any missions and
then deactivate it.

After you save your game
in the Start Menu, quit
using the PS Button.
*/
#