File Info
0
Eboot.Elf
/*
Decrypt this file instead.

\USRDIR\scimitar_final.self
*/
#
Infinite Oxygen Gauge
0
games24.blog.fc2.com/blog-entry-218.html
0 0176DC8C D0830080
#
Faster Reload (Can Not Use Dual Pistols)
0
games24.blog.fc2.com/blog-entry-218.html
0 014C2A98 60000000
0 014C2A9C 7C0B0378
#
Items Do Not Decrease Gold
0
games24.blog.fc2.com/blog-entry-218.html
0 018A5830 38800000
#
Sleep Never Ends
0
games24.blog.fc2.com/blog-entry-218.html
0 014A5CA4 C19F051C
#