Max Souls + Infinite Souls
0
Medo, Skiller
0 00AF0C6C 3D403E80
#
Reduce all Damage taken to 0
0
Medo
0 0199C790 60000000
0 0199C79C 60000000
#
Max Equipment Load
0
Medo
0 0199C71C 49499000
#
Max Stats, Defense, Resistance
0
Medo
0 0199C76C 49000000
#
Max Items on Use + Discard + Buy + Deposit in Storage
0
Medo
0 00AD3710 60000000
0 00AD3760 409DFFB4
#
Infinite Magic + Miracles + Pyromancy Slot 1
0
Medo
0 00ADBF5C 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot 2
0
Medo
0 00ADBF9C 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot 3
0
Medo
0 00ADBFDC 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot 4
0
Medo
0 00ADC01C 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot 5
0
Medo
0 00ADC05C 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot 6
0
Medo
0 00ADC09C 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot 7
0
Medo
0 00ADC0DC 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot 8
0
Medo
0 00ADC11C 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot 9
0
Medo
0 00ADC15C 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot 10
0
Medo
0 00ADC19C 30A90004
#