Max + Infinite Items
0
jgduff1
0 00250F04 90A3021C
/*
Do not take "all" items
when you buy something.
*/
#
Infinite Magic
0
jgduff1
0 001DFB08 909F01A8
#
Infinite Health
0
jgduff1
0 001DF3E4 D3FD019C
/*
You need to die in the
1st level, so activate it
after the 1st level.
*/
#
Level 99 On Level Up
0
jgduff1
0 00485300 93DC0010
#
Lot Of Money On Change
0
jgduff1
0 00492178 9003002C
0 004A37B0 911D0024
/*
Don't take "all" items
when you buy something.
*/
#