Alternative Names
0
PARAM.SFO
/*
Shin Sangoku Musou 5
*/
#
Instant Max + Infinite Musou (Hold O)
0
jgduff1
0 0019994C EC23682A
#
Memory Max Level On Exp Gain + High Stats
0
jgduff1
0 101DECE0 0000012C
#
ASM Max Level On Exp Gain + High Stats
0
jgduff1
0 00364094 90030098
#
Memory Max K.O. On 1 Kill
0
jgduff1
0 101ED6E8 0000270F
#
ASM Max K.O. On 1 Kill
0
jgduff1
0 00060B4C 905F00B0
#
Always Max + Infinite Skills Points
0
jgduff1
0 002DADA0 905FDF58
/*
Do not use on the 1st
mission.
*/
#