Memory Lot Of Nanite On Gain
0
jgduff1
0 32B93AFC 000000C8
#
ASM Lot Of Nanite On Gain
0
jgduff1
0 000DE768 7D220214
0 000DE76C 905C0004
#
Memory 1 Hit Kill + Health Bar Decreases But You Never Die
0
jgduff1
0 37641BC4 42C80000
/*
Never use it in Moto
Phase.
*/
#
ASM 1 Hit Kill + Health Bar Decreases But You Never Die
0
jgduff1
0 00072DAC 60000000
/*
Never use it in Moto
Phase.
*/
#
Memory Infinite Omega Power
0
jgduff1
0 37642FAC 43480000
#
ASM Infinite Omega Power
0
jgduff1
0 000DFE04 60000000
0 000DFE08 60000000
#
Memory Instant Omega Power
0
jgduff1
0 37642FAC 43480000
#
ASM Instant Omega Power
0
jgduff1
0 00190DA4 EFFF67BA
0 00190DAC D2C60004
#