Memory Instant Max Fury On Gain For Spyro
0
jgduff1
0 300FF824 00000FA0
#
ASM Instant Max Fury On Gain For Spyro
0
jgduff1
0 004FE254 7D275214
#
Memory Instant Max Fury On Gain For Cinder
0
jgduff1
0 300FF828 00000FA0
#
ASM Instant Max Fury On Gain For Cinder
0
jgduff1
0 004FE2DC 7D275214
#
Memory Max + Infinite Health On Change For Spyro
0
jgduff1
0 300FF7FC 0000012C
#
ASM Max + Infinite Health On Change For Spyro
0
jgduff1
0 004FDA7C 9043004C 
0 004FE05C 903D004C 
#
Memory Max + Infinite Health On Change For Cinder
0
jgduff1
0 300FF804 0000012C
#
ASM Max + Infinite Health On Change For Cinder + Infinite MP For Spyro
0
jgduff1
0 004FDACC 90430054
0 004FE140 903D0054
#
Memory Easy Max Orbs
0
jgduff1
0 300FF834 00000450
#
ASM Easy Max Orbs
0
jgduff1
0 005005BC 7C0B0214
#
Memory Max + Infinite Magic On Change For Spyro
0
jgduff1
0 300FF814 0000012C
#
ASM Max + Infinite Magic On Change For Spyro
0
jgduff1
0 004FD87C 91030064
0 004FDE0C 917D0064
#
Memory Max + Infinite Magic On Change For Cinder
0
jgduff1
0 300FF81C 0000012C
#
ASM Max + Infinite Magic On Change For Cinder
0
jgduff1
0 004FD8CC 9023006C
0 004FDEF0 903D006C
#