Versions note
0
bungholio
/*
BLES02169 v01.00 av01.01
+
BLUS31550 v01.00 av01.01
have a lot of differences
but by coincidence the
ASM codes are the same.

The memory codes might
work for
BLUS31550 v01.00 av01.01
but I can't test.
*/
#
ASM Lot + Infinite Pieces Of Lego On Gain
0
jgduff1
0 0125A840 FB3E0020
#
ASM Infinite Health 1
0
jgduff1
0 00D9FE5C 60000000
0 00DA0E90 60000000
0 00DA0E94 D03E0000
#
ASM Infinite Health 2
0
jgduff1
0 009700FC 60000000
/*
It also affects enemies.
*/
#