File Info
0
jgduff1
/*
You will be using either
EBOOT.BIN or MUA2.BIN,
I'm not sure of which
but the files are
identical.
*/
#
Memory Max Level + Strike + Teamwork + Body + Focus + Hit Points + Stamina On 1 Kill
0
jgduff1
0 313BB110 00000046
0 313BB4E0 000000A0
#
ASM Max Level + Strike + Teamwork + Body + Focus + Hit Points + Stamina On 1 Kill
0
jgduff1
0 0038783C 91490000
0 00387848 90430020
#
Memory Infinite Power Points
0
jgduff1
0 3138B394 003C
#
ASM Infinite Power Points
0
jgduff1
0 0021FA84 60000000
#
Memory Lot + Infinite Ability Points On Change
0
jgduff1
0 3138B398 0000014D
#
ASM Lot + Infinite Ability Points On Change
0
jgduff1
0 0021F390 90030008
#