File Info
0
bungholio
/*
These are very likely
for 01.02, but I cannot
confirm it.
*/
#
No Gun Firefighting Limit
0
nichecode.blog.fc2.com/blog-entry-120.html
0 007234C8 60000000
#
Shuffle Invalid
0
nichecode.blog.fc2.com/blog-entry-120.html
0 002CD224 48000160
/*
Uses the same address as
"Forced Killing".
*/
#
Forced Killing
0
nichecode.blog.fc2.com/blog-entry-120.html
0 002CD224 48000074
/*
Uses the same address as
"Shuffle Invalid".
*/
#
Co-op Conversation 1 Rank Up (Except For Mission Clearing)
0
nichecode.blog.fc2.com/blog-entry-120.html
0 00549704 60000000
#
999,999,999 Fishing Points
0
nichecode.blog.fc2.com/blog-entry-120.html
0 01080BA8 3B9AC9FF
#
Mentions Search Always Invoked
0
nichecode.blog.fc2.com/blog-entry-120.html
0 0029AD78 60000000
0 0029AD98 38600001
#
Persona Itemization Once A Day Unlimited
0
nichecode.blog.fc2.com/blog-entry-120.html
0 005F5CB0 48000014
#
Ammo Never Decreases
0
nichecode.blog.fc2.com/blog-entry-120.html
0 00723590 38800000
#