Memory Infinite Magic
0
jgduff1
0 33A62C30 449C4000
#
ASM Infinite Magic
0
jgduff1
0 0017B9EC EC210FFA
#
Memory No Waiting Time For Magic (Use One Time To Work)
0
jgduff1
0 33E5E4B4 BCE5AFDA
#
ASM No Waiting Time For Magic (Use One Time To Work)
0
jgduff1
0 0017FFF0 60000000
#
Memory Infinite Items
0
jgduff1
0 33942EEB 04
#
ASM Infinite Items
0
jgduff1
0 000A8270 30630000
#
Memory Max Level
0
jgduff1
0 32031F94 C5EC6925
0 320387A4 C5EC6925
#
ASM Max Level
0
jgduff1
0 0022FA2C D3F8000C
/*
There was a note stating
the code does not work,
but I was not sure of
which part did not work.
*/
#
Memory Infinite Health
0
jgduff1
0 33A626A0 442F0000
#
ASM Infinite Health
0
jgduff1
0 000851D8 60000000
0 00085224 60000000
/*
It also affects enemies.
*/
#