Memory Lot + Infinite Money On Gain
0
jgduff1
0 32AEADC0 00000010
#
ASM Lot + Infinite Money On Gain
0
jgduff1
0 001CBF54 90430000
#
Memory Max Level + Lot HP On 2 Kills
0
jgduff1
0 36F7774C 00000007
#
ASM Max Level + Lot HP On 2 Kills
0
jgduff1
0 000BC268 905B0000
#
Memory Lot + Infinite Skills Points On Use + Gain
0
jgduff1
0 3166DD64 0046
#
ASM Lot + Infinite Skills Points On Use + Gain
0
jgduff1
0 00086418 9B660000
#
Memory Infinite Potion
0
jgduff1
0 35C26132 0003
#
ASM Infinite Potion
0
jgduff1
0 001A5E20 30840000
0 001A5E2C 90850010 
#
Memory Instant Max + Infinite Special (Instant Max With Potion Only)
0
jgduff1
0 30E5FE98 42700000
0 31BA62C8 42700000
#
ASM Instant Max + Infinite Special (Instant Max With Potion Only)
0
jgduff1
0 000B5FFC EC20107A /*On Increase*/
0 000B6018 EC5F317A /*On Increase*/
0 000B601C EC4020BA /*On Increase*/
0 004112C4 60000000 /*On Decrease*/
#