Alternative Names
0
PARAM.SFO
/*
Saint Seiya I Cavalieri Dello Zodiaco La Battaglia Del Santuario
Saint Seiya Les Chevaliers Du Zodiaque La Bataille Du Sanctuaire
Saint Seiya Los Caballeros Del Zodiaco Batalla Por El Santuario
Saint Seiya Os Cavaleiros Do Zodiaco A Batalha Do Santuario
Saint Seiya Sanctuary Battle
Saint Seiya Senki
*/
#
Infinite Cosmo (MP)
0
vosman, JorgeFFC
0 00107A64 60000000
0 00107F5C 60000000
0 001086CC 60000000
0 001087A8 60000000
#
Infinite CP (Cosmo Points)
0
vosman, JorgeFFC
0 001CCE40 3CA04B18
0 001CCE44 60A5967F
0 001CCE54 90BE004C
#