Memory Infinite Health
0
jgduff1
0 34D27424 00000564
#
ASM Infinite Health
0
jgduff1
0 000AB41C 93520034
#
Memory Infinite Special Attack
0
jgduff1
0 34D2742C 447A0000
#
ASM Infinite Special Attack
0
jgduff1
0 000E0774 60000000 
#
Memory Special Attack + Fury Instant Recharge
0
jgduff1
0 34D2742C 447A0000
#
ASM Special Attack + Fury Instant Recharge
0
jgduff1
0 000B5834 D0A8003C
#
Memory Max Level On 1 Hit + High Health + Musou + Attack + Speed + Ride
0
jgduff1
0 008C654C 00000003
#
ASM Max Level On 1 Hit + High Health + Musou + Attack + Speed + Ride
0
jgduff1
0 0011B23C 919B0008
#
Memory Max Gold On Gain
0
jgduff1
0 008C6B40 0000012C
#
ASM Max Gold On Gain
0
jgduff1
0 00038CF0 90446B40
#
Memory Unknown Code 1
0
jgduff1
0 341D64A0 000003E8
#