Alternative Names
0
PARAM.SFO
/*
Atelier Shallie Alchemists Of The Dusk Sea
*/
#
Does not decrease MP
0
games24
0 002913F8 60000000
#
Not reduced items (in combat)
0
games24
0 001A12A4 60000000
#
Renkin Experience Multiplier
0
games24
0 001E802C 3063Z
[Z]000A=10x;0064=100x;03E8=1000x;2710=10000x[/Z]
#
Experience Multiplier
0
games24
0 001FAB34 1CA4Z
[Z]000A=10x;0064=100x;03E8=1000x;2710=10000x[/Z]
#
Not reduced material items (preparation time)
0
games24
0 00185890 60000000
#
Effect up to and to formulate
0
games24
0 0033586C 48000008
#
Field Gauge Max On Change
0
games24
0 0010D8B0 48000008
#
(Map moves and varying) motivation Max
0
games24
0 0025CAF0 48000008
#
Life task (free) progression Max
0
games24
0 0035C5D4 388003E7
#
Not a (free) attainment flag On life task 
0
games24
0 00093020 4800007C
/*
Flag become fine
achievement will not be
the main event ON is no
longer
I keep one main event 
*/
#
Flag to advance to the next chapter 1
0
games24
0 00C12A0C 01
#
Flag to advance to the next chapter 2
0
games24
0 00C12A0D 01
#
Life task (free) (free time) attainment flag Chapter 1
0
games24
0 00C13D8C 01
#
Life task (free) (free time) attainment flag Chapter 2
0
games24
0 00C13D8F 01
#
Not reduced PP (Renkin time)
0
games24
0 001EB2BC 60000000
#
Create Alchemy Item the real star of hoshi no mi
0
games24
0 00335B6C 38800000
#
Create Alchemy Item ore pumpkin
0
games24
0 00335B6C 38800001
#
Create Alchemy Item Sherubani wheat
0
games24
0 00335B6C 38800005
#
Create Alchemy Item Ogasa strawberry tree
0
games24
0 00335B6C 3880000D
#
Create Alchemy Item marbled beef
0
games24
0 00335B6C 38800017
#
Create Alchemy Item Suragakoa
0
games24
0 00335B6C 38800032
#
Create Alchemy Item Sea Sand of twilight
0
games24
0 00335B6C 3880003D
#
Create Alchemy Item Underground water of silver
0
games24
0 00335B6C 38800070
#
Create Alchemy Item Flower of defense
0
games24
0 00335B6C 38800072
#
Create Alchemy Item dried herbs
0
games24
0 00335B6C 388000D2
#
Create Alchemy Item neutralizer red
0
games24
0 00335B6C 388000D6
#
Create Alchemy Item leather
0
games24
0 00335B6C 388000E1
#
Create Alchemy Item Zetteru
0
games24
0 00335B6C 388000E2
#
Create Alchemy Item Suterado woven fabric
0
games24
0 00335B6C 388000E8
#