Memory Partial Infinite Health + One Hit Kills
0
jgduff1
0 3157CE70 43480000
0 35F180C0 3F800000
#
ASM Partial Infinite Health + One Hit Kills
0
jgduff1
0 00138D10 EFEAF028
0 00138D18 D15F0070
/*
It also affects enemies,
but they can still be
killed with guns,
chainsaws, and the big
jump attack.
*/
#
ASM Have Shotgun
0
jgduff1
0 0037E83C 60000000
#
Memory Infinite Grenades
0
jgduff1
0 377607D2 0004
0 378033F2 0004
#
ASM Infinite Grenades
0
jgduff1
0 0014EE04 39290000
#