Infinite Health
0
Hiei-YYH
0 001266A8 60000000
0 001266B4 60000000
#
Invincible (Use with Infinite Health)
0
Hiei-YYH
0 001266A0 386042C8
0 001266A4 B07F018A
#
Infinite Ammo
0
Hiei-YYH
0 001C1728 31080000
#
Infinite Supplies
0
Hiei-YYH
0 001C1EEC 30840000
#
Freeze Time
0
Hiei-YYH
0 001345D0 FC201090
#
Save Always 0
0
Hiei-YYH
0 00028D7C 30A50000
#
Max Enemies Killed By Weapons
0
Hiei-YYH
0 00134898 3880270F
/*
You must kill at least 1
enemy for this to work.
*/
#
No Enemies Killed By Weapons
0
Hiei-YYH
0 00134898 38800000
/*
You must kill at least 1
enemy for this to work.
*/
#
Max Enemies Killed By Melee
0
Hiei-YYH
0 00134910 3880270F
/*
You must kill at least 1
enemy for this to work.
*/
#
No Enemies Killed By Melee
0
Hiei-YYH
0 00134910 38800000
/*
You must kill at least 1
enemy for this to work.
*/
#