Alternative Names
0
PARAM.SFO
/*
Sleeping Dogs Hong Kong Himitsu Keisatsu
*/
#
Max Everything After Restarting From A Checkpoint Or Beating A Mission
0
Medo
0 00593D30 3CA07FFF
/*
Works for Exp, Money,
Statistics, more.
*/
#
Max Money
0
Medo
0 00581D14 3C607FFF
#
Max Money On Buy In Stores Only
0
Medo
0 005B5094 3D003B9A
0 005B5098 6108C9FF
0 005B509C 91070000
/*
Delete saved game options
or the game will not boot.
*/
#