Eboot Note
0
bungholio
/*
Coincidentally all of the
BLES00135 v01.00 av01.11
codes are in the same
location, so there's a
chance every memory code
from it would work too,
but I don't have the
games to personally test
and verify it.

Give them a try if you're
curious.
*/
#
ASM Infinite X
0
jgduff1
0 000730C4 39290000
0 000730C8 60000000
#
ASM Instant Easy Points + 5 Stars Rank
0
jgduff1
0 00073EB0 905F002C
#
ASM Infinite Time
0
jgduff1
0 0015AB60 60000000
#
ASM Max Scores Points
0
jgduff1
0 00073B58 7C02E214
#
ASM Gain 5 Stars After All Race
0
jgduff1
0 000731B0 EC1F682A
0 000731B4 EC1F682A
#
ASM String Bonus x9999
0
jgduff1
0 00073BE0 3929270F 
#