Money Multiplier
0
nichecode.blog.fc2.com/blog-category-12.html
0 0067C504 1C6300Z
[Z]000A=10x;0064=100x;03E8=1,000x;2710=10,000x[/Z]
#
AP Multiplier
0
nichecode.blog.fc2.com/blog-category-12.html
0 0067C520 1C6300Z
[Z]000A=10x;0064=100x;03E8=1,000x;2710=10,000x[/Z]
#
Experience Multipliers
0
nichecode.blog.fc2.com/blog-category-12.html
0 0067B364 1C6300Z /* Main unit display */
0 0067CEC0 1C6300Z /* Main unit actual */
0 0067B664 1C6300Z /* Sub unit display */
0 0067D480 1C6300Z /* Sub unit actual */
[Z]000A=10x;0064=100x;03E8=1,000x;2710=10,000x[/Z]
#
PP Multiplier
0
nichecode.blog.fc2.com/blog-category-12.html
0 0067B384 1C6300Z /* Main unit display */
0 0067CEA0 1C6300Z /* Main unit actual */
0 0067B684 1C6300Z /* Sub unit display */
0 0067D460 1C6300Z /* Sub unit actual */
[Z]000A=10x;0064=100x;03E8=1,000x;2710=10,000x[/Z]
#
Shots Multiplier
0
nichecode.blog.fc2.com/blog-category-12.html
0 006CE818 1F1800Z
[Z]000A=10x;0064=100x;03E8=1,000x;2710=10,000x[/Z]
#
Exp Never Decreases For Sub Units
0
nichecode.blog.fc2.com/blog-category-12.html
0 003EB4BC 60000000
#
PP Never Decreases For Sub Units
0
nichecode.blog.fc2.com/blog-category-12.html
0 003EE8E8 60000000
#
Exp Never Decreases For Map Weapons
0
nichecode.blog.fc2.com/blog-category-12.html
0 003EB2D8 7F800000
#
PP Never Decreases For Map Weapons
0
nichecode.blog.fc2.com/blog-category-12.html
0 003EE80C 7F800000
#
Sub-Pilot PP Halved
0
nichecode.blog.fc2.com/blog-category-12.html
0 003EE81C 7E6B9B78
#
SR PP Amount Modifier
0
nichecode.blog.fc2.com/blog-category-12.html
0 004F4350 38A0A
[Z]000A=Default 10;0064=100;03E8=1,000;2710=10,000[/Z]
#
General Purpose Full Remodeling Bonus Resettable
0
nichecode.blog.fc2.com/blog-category-12.html
0 0091D050 60000000
0 00924124 7C000000
#
Transit Limit Release
0
nichecode.blog.fc2.com/blog-category-12.html
0 0014C564 7C7900D0
0 001EE630 60630001
/*
You can not transfer to a
battleship.


Modified to be able to
switch to enemy aircraft,
and now it is possible to
switch to battleships as
a side effect.


However, I think that it
will only freeze if you
switch to a battleship,
or forcefully return to
the original captain.


Please be aware that if
you put a subpilot on a
unit, it will freeze
immediately.


Other than that, no
detailed verification has
been conducted.
*/
#
All Aircraft Reinforcement Parts Frame 4
0
nichecode.blog.fc2.com/blog-category-12.html
0 001DECC0 38600004
0 009AD3EC 38600004
0 00821918 3B200004
0 0082317C 3B600004
0 009A96F4 38C00004
0 009ACFAC 3B600004
0 009B2534 3B600004
0 009E22B0 3B400004
0 00A422FC 3BE00004
/*
The first two lines are
the code that is
essential for the code to
be effective.


To demonstrate the effect
of the parts equipped to
exceed the actual number
of frames.
To strengthen the frame
equipped parts frame to 4
frames.
Enhanced parts frame
normal display of the
aircraft ability screen.
Enhanced parts frame
normal display of the
unit ability screen.
Unit formation screen 
reinforcement parts frame
normal display /
reinforcement parts
equipment screen
reinforcement parts frame
normal display.
Equipment body selection
screen simple status
screen reinforcement
parts frame normal
display.
Equipment body selection
screen number parts
reinforcement parts frame
normal display is.
*/
#
All Skills Can Be Acquired
0
nichecode.blog.fc2.com/blog-category-12.html
0 0083BE60 38600001
0 008D70F8 38600001
/*
Skills that can not be
acquired normally, such
as lucky and infight
level system, only 1
level can be acquired.
*/
#
Can Overwrite Skills
0
nichecode.blog.fc2.com/blog-category-12.html
0 008DE74C 3BA00001
#
All Units Weapon Gauge 999
0 002067B8 386003E7
/*
It will show when loading
saved data by
intermission once after
activating the code.


This does not save.


You can change the 03E7
part to a value of your
choice.
*/
#
Necessary Funds 0 When Remodeling The Unit
0
nichecode.blog.fc2.com/blog-category-12.html
0 0091C2F0 3B800000
0 0091CFB8 40BC04C8
/*
With the bug that can not
be changed to the unit
before and after with the
LR button on the
remodeling screen.
*/
#
Necessary Fund 0 At The Time Of Retrofit Weapon Remodeling
0
nichecode.blog.fc2.com/blog-category-12.html
0 00889BE4 38600000
#
Required AP At Purchase Of Ability
0
nichecode.blog.fc2.com/blog-category-12.html
0 00145C60 38600000
#
Required When Acquiring Skills PP0
0
nichecode.blog.fc2.com/blog-category-12.html
0 008D696C 38600000
0 008DD710 38600000
0 008DDB1C 38600000
#
When The Capacity Value Rises, It Can Be Executed Even If The PP Is Insufficient
0
nichecode.blog.fc2.com/blog-category-12.html
0 008DE7F4 7F000000
/*
PP itself consumes to 0.
*/
#
PP0 Consumed When Capacity Value Rises
0
nichecode.blog.fc2.com/blog-category-12.html
0 0027E7D0 38600000
0 008D9104 38600000
#
Memory Money 99,999,999
0
nichecode.blog.fc2.com/blog-category-12.html
0 300D07C8 05F5E0FF
#
Memory Total Acquired Money 99,999,999
0
nichecode.blog.fc2.com/blog-category-12.html
0 300D07CC 05F5E0FF
#
Memory AP 99,999,999
0
nichecode.blog.fc2.com/blog-category-12.html
0 300D07D0 05F5E0FF
#
Memory Total Acquired AP 99,999,999
0
nichecode.blog.fc2.com/blog-category-12.html
0 300D07D4 05F5E0FF
#
Memory Total Number Of Abilities
0
nichecode.blog.fc2.com/blog-category-12.html
0 300D0BD6 7F7F /* Fighting */
0 300D0BFE 7F7F /* Range */
/*
Add 0x2 to the addresses
to get to the next
ability.

The order of abilities is
the same as the order of
"sorted by abilities" on
the purchase screen.
*/
#
Memory Number Of Abilities Not Equipped
0
nichecode.blog.fc2.com/blog-category-12.html
0 300D0AB2 7F7F /* Fighting */
0 300D0ADA 7F7F /* Range */
/*
Add 0x2 to the addresses
to get to the next
ability.
*/
#
Memory Total Number Of Parts
0
nichecode.blog.fc2.com/blog-category-12.html
0 300D0B95 7F
0 300D0BBF 7F
/*
Add 0x1 to the addresses
to get to the next part.

Since the order of
reinforced parts is
different from the sort
order, please check the
list in
"\Special\SRWOG_MD_List.xml".
*/
#
Memory Number Of Reinforced Parts Not Equipped
0
nichecode.blog.fc2.com/blog-category-12.html
0 300D0A71 7F
0 300D0A9B 7F
/*
Add 0x1 to the addresses
to get to the next part.

Since the order of
reinforced parts is
different from the sort
order, please check the
list in
"\Special\SRWOG_MD_List.xml".
*/
#
Mental Command Required SP0
0
nichecode.blog.fc2.com/blog-category-12.html
0 001EB9B4 38600000
0 001F26A0 38600000
#
All Mental Commands Can Be Used Regardless Of Level
0
nichecode.blog.fc2.com/blog-category-12.html
0 001E397C 38600000
#
Mental Command Change
0
nichecode.blog.fc2.com/blog-category-12.html
/* 1st */
0 00659084 380000Z
/* 2nd */
0 006591B0 380000Z
/* 3rd */
0 00729224 392000Z
/* 4th */
0 006592A0 392000Z
/* 5th */
0 0065931C 392000Z
/* Twin Spirit */
0 00659398 396000Z
/*
While the code is on,
change the target number
mental command of all
characters to Z.


The mental command ID is
entered in Z.


Please check the ID in
the list at
"\Special\SRWOG_MD_List.xml".
*/
#
Movement + Acceleration Power Of All Units
0
nichecode.blog.fc2.com/blog-category-12.html
0 001485FC Z
[Z]88690012=Off;38600063=I don't know[/Z]
/*
This also works for
enemies, so you will need
to disable it as needed.
*/
#
All Weapons_P Weapon Judgment
0
nichecode.blog.fc2.com/blog-category-12.html
0 0013AE70 Z
[Z]8863001F=Off;38600001=On[/Z]
/*
This also works for
enemies, so you will need
to disable it as needed.
*/
#
All Weapons, No Need For Skills
0
nichecode.blog.fc2.com/blog-category-12.html
0 0013AFD8 Z
[Z]88630016=Off;38600000=On[/Z]
/*
This also works for
enemies, so you will need
to disable it as needed.
*/
#
All Weapons, No Skills Required
0
nichecode.blog.fc2.com/blog-category-12.html
0 0013AC78 Z
[Z]8863002E=Off;38600000=On[/Z]
/*
This also works for
enemies, so you will need
to disable it as needed.
*/
#
All Weapons, Necessary Skill Level 1
0
nichecode.blog.fc2.com/blog-category-12.html
0 0013B740 Z
[Z]8863002F=Off;38600001=On[/Z]
/*
This also works for
enemies, so you will need
to disable it as needed.
*/
#
All Weapons, Terrain Adaptation Change
0
nichecode.blog.fc2.com/blog-category-12.html
/* Sky */
0 0013AF6C Z
/* Land */
0 0013AF48 ZZ
/* Sea */
0 0013AF24 ZZZ
/* U */
0 0013AF00 ZZZZ
[Z]8863001B=Off;38600000=None;38600001=1;38600001=2;38600001=3;38600001=4;38600001=5[/Z]
[ZZ]8863001C=Off;38600000=None;38600001=1;38600001=2;38600001=3;38600001=4;38600001=5[/ZZ]
[ZZZ]8863001D=Off;38600000=None;38600001=1;38600001=2;38600001=3;38600001=4;38600001=5[/ZZZ]
[ZZZZ]8863001E=Off;38600000=None;38600001=1;38600001=2;38600001=3;38600001=4;38600001=5[/ZZZZ]
/*
This also works for
enemies, so you will need
to disable it as needed.
*/
#
All Weapons Special Effects 1 And 2 Are Added
0
nichecode.blog.fc2.com/blog-category-12.html
0 0013ACC0 Z
0 0013AC9C ZZ
0 0013B768 ZZZ
[Z]8863002B=Off;38600000=I don't know[/Z]
[ZZ]8863002C=Off;38600000=I don't know[/ZZ]
[ZZZ]8863002D=Off;38600000=I don't know[/ZZZ]
/*
This also works for
enemies, so you will need
to disable it as needed.


Please check the ID of
special effects 1 and 2
in the list at
"\Special\SRWOG_MD_List.xml".


You will need to manually
modify the values of this
code as needed.


Add armor down etc to all
weapons.


The value of Z is from
above the special effect
2 ID (such as barrier
penetration).


Special effect 1 ID
(Armor down etc)


Special effect 1 Level
Enters.


If there is no concept of
Level in Special Effect
1, such as movement down,
put 0x0 in the Level
column.
*/
#
All Map Weapons Add Enemy Identification
0
nichecode.blog.fc2.com/blog-category-12.html
0 0013AE94 Z
[Z]88630032=Off;38600001=On[/Z]
/*
This also works for
enemies, so you will need
to disable it as needed.
*/
#
Memory 99 Unit Number Change
0
nichecode.blog.fc2.com/blog-category-12.html
0 300D0564 63
#
Additional Pilot
0
nichecode.blog.fc2.com/blog-category-12.html
0 00E52120 F821FF31
0 00E52124 7C6802A6
0 00E52128 FB6100C8
0 00E5212C 906100C0
0 00E52130 3CA00029
0 00E52134 60A5B3D4
0 00E52138 7D051800
0 00E5213C 408A00B8
0 00E52140 3F600100
0 00E52144 936100BC
0 00E52148 807B0000
0 00E5214C 2D030000
0 00E52150 408A00A4
0 00E52154 3F60300C
0 00E52158 637BB5B8
0 00E5215C 38800000
0 00E52160 64838000
0 00E52164 80BB0000
0 00E52168 7D051840
0 00E5216C 41A80010
0 00E52170 38840020
0 00E52174 3B7B0004
0 00E52178 4BFFFFEC
0 00E5217C 29050000
0 00E52180 418A0010
0 00E52184 38840001
0 00E52188 54A5F87E
0 00E5218C 4BFFFFF0
0 00E52190 2D0400C0
0 00E52194 40880058
0 00E52198 1C84004C
0 00E5219C 908100B8
0 00E521A4 38E00000
0 00E521A8 3C603009
0 00E521AC 60639370
0 00E521B0 38A00000
0 00E521B8 39000000
0 00E521BC 4B362D79
0 00E521C0 808100B8
0 00E521C4 3C60300C
0 00E521C8 606369B8
0 00E521CC 7C632214
0 00E521D0 38800001
0 00E521D4 98830020
0 00E521DC B0830006
0 00E521E8 90830008
0 00E521EC 836100BC
0 00E521F0 903B0000
0 00E521F4 EB6100C8
0 00E521F8 806100C0
0 00E521FC 382100D0
0 00E52200 7C6803A6
0 00E52204 4E800020
/* Numerical designation section */
0 01000000 00000000
0 00E521A0 388000Z
0 00E521B4 38C0000ZZ
0 00E521D8 388000ZZZ shooting
0 00E521E0 3C80ZZZZ EXP
0 00E521E4 6084ZZZZZ PP
0 001816A0 48CD0A80
/*
Somebody else will need
to figure this entire
thing out, I'm no
translator and cannot set
up the values or
anything.


Numeric designation section
Z = pilot ID
ZZ = Initial ability equipment flag (0 = not equipped / 1 = equipped)
ZZZ = number of shots
ZZZZ = EXP
ZZZZZ = PP

Please check the pilot ID in the " niche_code code " list.

OFF code is the same as "Add optional unit"

how to use

Add in almost the same way as adding a unit

Open the unit formation screen with the "Required" code and the "Num. Designated part" code turned ON, and when you cancel with the quick X button, the change confirmation screen will be displayed, so select "Yes". (If you select "Abort and exit" here, the addition of the pilot will also be canceled)

At this point, it does not appear on the pilot list yet.

After that, pilots will be added if you perform "Replacement" with appropriate pilots.


For the second and subsequent pilot additions, change the "numeric designation part" code until the game is over and apply only the "required" code (except when using the "arbitrary unit addition" code). "Required" code also needs to apply)


Notes
1. "Add optional unit" and "Add optional pilot" can not be used simultaneously. (Requires additional work on the code application and unit formation screen individually)

2. The added pilot will appear on the main side of the unit with the lowest number available.
Since it does not appear on the sub side, when adding multiple pilots, please do the front filling work to the sub side and note the number of remaining units.

3. If you have added an enemy pilot, you can not change as it is, so use the "Change transfer restriction code" together.
*/
#
Old Additional Unit
0
nichecode.blog.fc2.com/blog-category-12.html
0 01000000 00000000
0 00E52120 9421FFF0
0 00E52124 7C6802A6
0 00E52128 90610000
0 00E5212C 3CA00029
0 00E52130 60A5B3D4
0 00E52134 7D051800
0 00E52138 408A00C0
0 00E5213C 3F600100
0 00E52140 93610004
0 00E52144 807B0000
0 00E52148 2D030000
0 00E5214C 408A00AC
0 00E52150 3F60300B
0 00E52154 637B7780
0 00E52158 38800000
0 00E5215C 64838000
0 00E52160 80BB0000
0 00E52164 7D051840
0 00E52168 41A80010
0 00E5216C 38840020
0 00E52170 3B7B0004
0 00E52174 4BFFFFEC
0 00E52178 29050000
0 00E5217C 418A0010
0 00E52180 38840001
0 00E52184 54A5F87E
0 00E52188 4BFFFFF0
0 00E5218C 2D0400C0
0 00E52190 40880068
0 00E52194 3884FFFF
0 00E52198 1C8401E4
0 00E5219C 3C603009
0 00E521A0 60639564
0 00E521A4 7C632214
0 00E521A8 38800001
0 00E521AC 9883001C
0 00E521B0 3B60000Z /* number of forms */
0 00E521B4 38800ZZ /* unit ID */
0 00E521B8 9081000C
0 00E521BC 38E00001
0 00E521C0 3C603009
0 00E521C4 60639370
0 00E521C8 38A00000
0 00E521CC 38C0000ZZZ /* initial ability equipment flag */
0 00E521D0 3900000ZZZZ /* Initial conversion weapon equipment flag */
0 00E521D4 4B37AF89
0 00E521D8 3B7BFFFF
0 00E521DC 8081000C
0 00E521E0 38840001
0 00E521E4 38E00000
0 00E521E8 2D1B0000
0 00E521EC 408AFFCC
0 00E521F0 83610004
0 00E521F4 903B0000
0 00E521F8 80610000
0 00E521FC 38210010
0 00E52200 7C6803A6
0 00E52204 4E800020
0 001816A0 48CD0A80
/*
Please check the ID stuff
in the list at
"\Special\SRWOG_MD_List.xml".


I cannot figure out how
to translate all of this
correctly and do the
digit choices, you will
need to modify this to
work how you want on your
own.


Open the unit formation
screen with the code
turned on, and if you
cancel with the quick X
button, the change
confirmation screen will
be displayed, so select
"Yes". If you select
"Abort and exit" here,
the addition of the
aircraft will also be
canceled.


It does not appear on the
aircraft list at this
point.


After that, the aircraft
is additionally displayed
when performing
"transfer" with a
suitable pilot. If an
additional unit holds a
retrofit weapon, it will
be added even if you
remove the retrofit
weapon with an
appropriate unit. Not
added for stripping
abilities.


Be sure to turn off the
code after use. If
possible, please turn it
off before changing it.


Even if you add an enemy
unit, you can not switch
as it is, so please use
the “unchangeable
transfer restriction”
code.


0 00E521B0 3B60000Z
Enter the number of units
to be added in "Z" here.
For example, add 0x2
including G Hawk if
Grungust style is used,
0x3 including G raptor
and G bison if Grungust
type is included.


0 00E521B4 38800ZZ
Enter the unit ID to be
added in "ZZ". For a
unit with multiple forms,
enter the top ID of the
form. 0x01D if Grungasuto
type is used, 0x021 if it
is used type.


00E521CC 38C0000ZZZ
00E521D0 3900000ZZZZ

Please put 0x0 or 0x1 in
"ZZZ" and "ZZZZ" here
respectively. When 0x1
is inserted, if the unit
to be added has the
initial equipment
"ZZZ" = "ability" and
"ZZZ" = retrofit weapon,
it is added as equipped.
In the case of 0x0, it is
not equipped and is
added.


Notes
1.
I found a way to add a
retrofit unit, so I
added an explanation
below.


2.
You can not add units
with multiple forms whose
ID is not a sequential
number (though I think it
is probably only the R
series). This is for
compression of the number
of lines in the code, but
I think that it will not
work if it is added more
than 1 in the R series
anyway or it will freeze
at the time of transfer.


3.
When a deformation unit
causes units of the same
ID to be dispatched to
the same map, the other
units disappear from the
screen (or twins in the
case of twins) at the
moment one unit is
deformed. I confirmed
with the Grungast Kai and
the Grungast ceremony. I
did not freeze
immediately, but I do not
know what will happen if
I clear the map as it is.


4.
If there is a single unit
or multiple units with
the same ID unit,
something may be wrong.
There was no problem at
the point where we
confirmed XN-L with 2
aircraft, but the pilot
specific aircraft such as
the main aircraft may be
dangerous.


5.
It will be reflected in
the save data.


6.
You can not delete the
added unit. Once if the
total number of units
flag is reduced, the
units after the flag will
be overwritten when the
next unit is added, but
the units normally added
during the game may also
be erased by overwriting.
If the corresponding unit
does not exist, it seems
that it will be newly
added without
modification, so there is
no problem if there is no
problem. It was confirmed
that there are 255 unit
data storage frames, so
there is no problem with
adding them. As a
precaution, if the total
number of units is 200 or
more, the code is limited
so that it can not be
added.


7.
I can not be held
responsible for freezes
or corrupted data. It
seems that there is no
problem because the unit
addition processing
itself is passing an
argument to the addition
processing routine, but
there is a possibility
that freezes and data may
be wrong, since it is
hard to carry out other
detailed parts.


How to add a retrofit
unit. Unlike a
transformation / merge
system, a retrofit unit
seems to have to "add
retrofit parts as one
unit". In other words, in
the case of three types
of units like mass
production type gesch,
"The actual unit data 3
units" + "the unit data 3
units of the retrofit
parts" = use a total of 6
units of data frame; The
unit enclosed in [] in
the unit ID list is
replacement part data.
Since it is all like
serial numbers, the
addition method does not
change and the start
number ID of the serial
number in the form number
"ZZ" including the
replacement parts in "Z"

Please put Example:
Mass production type Gespenst Mk-2 Kai (green) type N & G & C → Z = 0x6, ZZ = 0x02D
Eyre Chevalier & Jeanne Chevalier → Z = 0x3, ZZ = 0x081
*/
#