ASM Character 1 Infinite Health
0
jgduff1
/*
Unknown, I keep coming
back to 0 00067214 but
things have changed.
The value 907E02CC is
close but I do not know
if this is correct. The
area seems correct, I'm
just not sure what needs
to be done due to
changes.
*/
#
ASM Max + Infinite CP
0
jgduff1
0 0010AF78 931F0224
0 005C88C8 60000000
0 005C88CC 60000000
0 005C88D0 60000000
#
ASM Infinite Items
0
jgduff1
0 0021F988 B0C30002
#
ASM Infinite EP
0
jgduff1
0 0010A8C4 93FE0220
#