Infinite Health ( enable at main menu to avoid freeze )
0
Medo ported by Randy97Killa
0 007CAF50 486C0D24
0 00E8BC74 3A20008C
0 00E8BC78 923F0030
0 00E8BC7C 923F0038
0 00E8BC80 923F0044
0 00E8BC84 4B93F2D0
#
Infinite Everything (Ammo, Items, Skills, Parts)
0
Medo ported by Randy97Killa, Improved by illusion
0 0003495C 60000000
#
Max tools level
0
illusion
0 00082960 38000005
0 00082788 60000000
#
Infinite Ammo + Bottomless Clip (No Reload)
0
Medo ported by Randy97Killa
0 006B1D94 60000000
#
Infinite Flamethrower
0
Medo ported by Randy97Killa
0 006B9148 60000000
0 006B6AD0 60000000
#
Infinite Oxygen
0
Medo ported by Randy97Killa
0 0053AE78 60000000
#
Enemies Ignore Everything
0
bungholio ported by Randy97Killa
0 000CD6BC 48000010
0 000CD6D4 48000010
/*
All monsters and humans
will ignore you. They
patrol and everything, you
can walk into them, hurt
them, make noise, drop a
body in front of a human,
whatever, they continue on
like nothing happened.
*/
#
Enemies Never Grab Nor Melee
0
bungholio ported by Randy97Killa
0 005D5B3C 4E800020
/*
Humans still shoot and
bloaters still throw
stuff, otherwise they will
run around you in circles.
*/
#
Flashlight Never Dies
0
bungholio ported by Randy97Killa, Improved by ZEROx
0 006ACBC8 60000000
#
Auto Shiv Monsters
0
bungholio ported by Randy97Killa
0 00A223E4 00000D2C
#
Money $999,999,999 In Wallet
0
Medo ported by Randy97Killa
0 002F78C8 3CA03B9A
0 002F78CC A60A5C9F
0 002F78D0 F7FA3EB7
#