Homer Lives
0
crapulecorp
0 35059E49 64
#
Homer Health
0
crapulecorp
0 35059F8B 28
#
Homer Invincible
0
crapulecorp
0 35059F8B 28
0 35059FAE 01
#
Homer Weapon Modifier
0
crapulecorp
0 35059FB0 Z
[Z]06=Broom;07=Hammer;08=Catapult[/Z]
#
Marge Lives
0
crapulecorp
0 35059E41 64
#
Marge Health
0
crapulecorp
0 35059ECB 28
#
Marge Invincible
0
crapulecorp
0 35059ECB 28
0 35059EEE 01
#
Marge Weapon Modifier
0
crapulecorp
0 35059EF0 Z
[Z]00=Vacuum;06=Broom;07=Hammer;08=Catapult[/Z]
#
Bart Lives
0
crapulecorp
0 35059E51 64
#
Bart Health
0
crapulecorp
0 3505A04B 28
#
Bart Invincible
0
crapulecorp
0 3505A04B 28
0 3505A06E 01
#
Bart Weapon Modifier
0
crapulecorp
0 3505A070 Z
[Z]00=Skateboard;06=Broom;07=Hammer;08=Catapult[/Z]
#
Lisa Lives
0
crapulecorp
0 35059E59 64
#
Lisa Health
0
crapulecorp
0 3505A10B 28
#
Lisa Invincible
0
crapulecorp
0 3505A10B 28
0 3505A12E 01
#
Lisa Weapon Broom
0
crapulecorp
0 3505A130 Z
[Z]00=Jump Rope;06=Broom;07=Hammer;08=Catapult[/Z]
#