File Info
0
Eboot.Elf
/*
Decrypt this file instead.

\USRDIR\game2\timecrisis4.elf
*/
#
Memory Infinite Ammo + No Reload
0
jgduff1
0 3070B2B8 00000009
#
ASM Infinite Ammo + No Reload
0
jgduff1
0 0016EBC8 390B0000
#
Memory Infinite Life
0
jgduff1
0 3070AC0C 00000003
#
ASM Infinite Life
0
jgduff1
0 00172800 3B890000
#
Memory Max Scores On 1 Kil
0
jgduff1
0 3070AC08 0098967F
#
ASM Max Scores On 1 Kil
0
jgduff1
0 0017B71C 91BF0220
#