Alternative Names
0
PARAM.SFO
/*
Uncharted 3 Drake's Deception
Uncharted 3 La Traición De Drake
Uncharted 3 L'illusion De Drake
Uncharted 3 L'inganno Di Drake
Uncharted 3 Oszustwo Drake'a
*/
#
Dev Menu
0
dron_3 + HdHereidme
0 00737E4C 38000001
0 00737E50 980B2163
/*
L3 + Start = Dev Menu
L3 + Select = Quick Menu
L3 + Triangle = Debug Text
L2 + R2 = Debug Fly
*/
#
Infinite HP
0
CodeUnique3
0 00479CD8 60000000
#
Infinite Weapon
0
CodeUnique3
0 006E4284 60000000
#
AoB Dev Menu
0
dron_3 + HdHereidme
B 00010000 04000000
B 2F800000419E00A4839E8078 38000001980B2163839E8078
/*
L3 + Start = Dev Menu
L3 + Select = Quick Menu
L3 + Triangle = Debug Text
L2 + R2 = Debug Fly
*/
#