Also known as
Uncharted 2 Il Covo Dei Ladri
Uncharted 2 Honor Among Thieves
Uncharted Ougontou To Kieta Sendan

#
Dev Menu
0
dron_3 + HdHereidme
0 00794D34 38000001
0 00794D38 981821C8
0 00794D3C 480002A0
/*
L3 + Start = Dev Menu
L3 + Select = Quick Menu
L3 + Triangle = Debug Text
L2 + R2 = Debug Fly
*/
#
AoB Dev Menu
0
dron_3 + HdHereidme
B 00010000 04000000
B 881821C82F800000409E02A0 38000001981821C8480002A0
/*
L3 + Start = Dev Menu
L3 + Select = Quick Menu
L3 + Triangle = Debug Text
L2 + R2 = Debug Fly
*/
#