Memory Infinite Health
0
jgduff1
0 00E8FD18 44A28000
#
ASM Infinite Health
0
jgduff1
0 00400BB0 60000000
/*
Enemies can only be
killed with grenades or
special attacks.

1 of the turrets in level
2 cannot be killed with
this code active.
*/
#
Memory Max Points + All Weapons + All Bonus On 1 Hit
0
jgduff1
0 352A2298 00000546
#
ASM Max Points + All Weapons + All Bonus On 1 Hit
0
jgduff1
0 00260D68 937E00C8
#
ASM Infinite Special Attack
0
jgduff1
0 00267FB8 60000000
#
ASM Infinite Grenades On Gain
0
jgduff1
0 001AAFBC 92DC0070
#
Memory Max Artifacts On Gain
0
jgduff1
0 352A05E6 07
0 352A065E 07
#