Alternative Names
0
PARAM.SFO
/*
Anubis Zone Of The Enders
*/
#
File Info
0
Eboot.Elf
/*
Decrypt this file instead.

\USRDIR\ZoE2\ZoE2_ProjectFinal_DVD.ppu
*/
#
Memory Infinite Health
0
jgduff1
0 10BB2A3E 03E8 /*Numeric On Start Menu*/
0 10CDCF96 03E8 /*On Game Bar Health*/
#
ASM Infinite Health
0
jgduff1
0 00626A40 60000000
#
Memory Max Level + Energy + Sub Energy On One Kill
0
jgduff1
0 10B1A76C 00000BE5 /*Numeric On Start Menu*/
0 11B87F7C 00000BE6
#
ASM Max Level + Energy + Sub Energy On One Kill
0
jgduff1
0 00658830 90E4653C
#