Also known as
Ar Nosurge Umareizuru Hoshi E Inoru Uta

#
Delta 999,999 Exp
0
hohowan
0 00ABCEA4 000F423F
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Delta 10 AP + Turn Number
0
hohowan
0 00ABD084 0000000A
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Delta 999 Attack Power
0
hohowan
0 00ABD088 000003E7
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Delta 100 Defense Power
0
hohowan
0 00ABD08C 00000064
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Delta 999 Burst Effect
0
hohowan
0 00ABD094 000003E7
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Cass 999,999 Exp
0
hohowan
0 00ABD07C 000F423F
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Cass 9,999 HP + Endurance
0
hohowan
0 00ABCEC0 0000270F
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Cass 100 Defense Power
0
hohowan
0 00ABCEC4 00000064
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Cass 100 Power Effect
0
hohowan
0 00ABCEC8 00000064
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Cass 999 Fill Speed
0
hohowan
0 00ABCECC 000003E7
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Cass 999 Barrier Regen
0
hohowan
0 00ABCED0 000003E7
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Ion 999,999 Exp
0
hohowan
0 00ABCF90 000F423F
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Ion 9,999 HP + Endurance
0
hohowan
0 00ABCFAC 0000270F
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Ion 100 Defense Power
0
hohowan
0 00ABCFB0 00000064
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Ion 100 Power Effect
0
hohowan
0 00ABCFB4 00000064
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Ion 999 Fill Speed
0
hohowan
0 00ABCFB8 000003E7
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Ion 999 Barrier Regen
0
hohowan
0 00ABCFBC 000003E7
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Earthes Exp
0
hohowan
0 00ABD168 000F423F
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Earthes 10 AP + Turn Number
0
hohowan
0 00ABD170 0000000A
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Earthes 999 Attack Power
0
hohowan
0 00ABD174 000003E7
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Earthes 100 Defense Power
0
hohowan
0 00ABD178 00000064
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Earthes 999 Burst Effect
0
hohowan
0 00ABD180 000003E7
/*
To activate, go to the triangle
menu, enter equipment,
then open the "Strengthen
Defense (RNA)" menu.
*/
#
Have 99 Of All Food Items
0
hohowan
0 00ABCBB8 63
0 00ABCBBB 63636363
0 00ABCBC0 63636363
0 00ABCBC6 63
0 00ABCBC8 6363
0 00ABCBCD 63
0 00ABCBD2 63
0 00ABCBD9 636363636363636363636363
0 00ABCC25 63
0 00ABCC3E 63
#
Have 99 Of All General Items
0
hohowan
0 00ABCBE5 636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363
0 00ABCC17 63
0 00ABCC2C 63
0 00ABCC31 63
0 00ABCC60 636363636363636363636363
#
Have 99 Of All Medicine Items
0
hohowan
0 00ABCC12 6363636363
0 00ABCC18 6363636363636363636363636363
0 00ABCC26 636363636363
0 00ABCC2D 63636363
0 00ABCC32 636363636363636363636363
#
Have 99 Of All Mecha Items
0
hohowan
0 00ABCC3F 636363636363636363636363636363636363636363636363636363636363636363
#
Have 99 Of All Plugin Items
0
hohowan
0 00ABCC6C 636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363636363
#
99 Future Food
0
hohowan
0 00ABCBB8 63
#
99 Sukiyucky
0
hohowan
0 00ABCBBB 63
#
99 Eggstreme Tart
0
hohowan
0 00ABCBBC 63
#
99 Chicken & Egg! Bowl
0
hohowan
0 00ABCBBD 63
#
99 Irritating Ice
0
hohowan
0 00ABCBBE 63
#
99 One Hit KO Parfait
0
hohowan
0 00ABCBC0 63
#
99 Woobly Glace
0
hohowan
0 00ABCBC1 63
#
99 Akiko Sarumi
0
hohowan
0 00ABCBC2 63
#
99 Fruit Ponta
0
hohowan
0 00ABCBC3 63
#
99 Expanding Happy Soda
0
hohowan
0 00ABCBC6 63
#
99 Obstinate Bibimbap
0
hohowan
0 00ABCBC8 63
#
99 Nyurocky
0
hohowan
0 00ABCBC9 63
#
99 Catty Lunch
0
hohowan
0 00ABCBCD 63
#
99 Coffe Rice
0
hohowan
0 00ABCBD2 63
#
99 Pepotato
0
hohowan
0 00ABCBD9 63
#
99 Rocky
0
hohowan
0 00ABCBDA 63
#
99 Sham Flour
0
hohowan
0 00ABCBDB 63
#
99 Ponta Kalimantan
0
hohowan
0 00ABCBDC 63
#
99 Sweet Stick
0
hohowan
0 00ABCBDD 63
#
99 Salty Frost
0
hohowan
0 00ABCBDE 63
#
99 Floral Milk
0
hohowan
0 00ABCBDF 63
#
99 Ice Crystal
0
hohowan
0 00ABCBE0 63
#
99 Obonne Cake
0
hohowan
0 00ABCBE1 63
#
99 Meat
0
hohowan
0 00ABCBE2 63
#
99 Garlicue
0
hohowan
0 00ABCBE3 63
#
99 Golden Pepper
0
hohowan
0 00ABCBE4 63
#
99 Twister Lunch
0
hohowan
0 00ABCC25 63
#
99 Sharly Meat
0
hohowan
0 00ABCC3E 63
#
99 Merciless Detergent
0
hohowan
0 00ABCBE5 63
#
99 Flap Chunpost
0
hohowan
0 00ABCBE6 63
#
99 Empress Garment
0
hohowan
0 00ABCBE7 63
#
99 Chunpi
0
hohowan
0 00ABCBE8 63
#
99 Nyaroki
0
hohowan
0 00ABCBE9 63
#
99 Chirping Clock
0
hohowan
0 00ABCBEA 63
#
99 Chunpi Costume
0
hohowan
0 00ABCBEB 63
#
99 Arbitrator's Law Book
0
hohowan
0 00ABCBEC 63
#
99 Weak Magnetic Stud
0
hohowan
0 00ABCBED 63
#
99 Sandals of Happiness
0
hohowan
0 00ABCBEE 63
#
99 Super Rare Bronze Statue
0
hohowan
0 00ABCBEF 63
#
99 "That" Bronze Statue
0
hohowan
0 00ABCBF0 63
#
99 Unembarassing Panties
0
hohowan
0 00ABCBF1 63
#
99 Robot Bear
0
hohowan
0 00ABCBF2 63
#
99 Red Cow of Promise
0
hohowan
0 00ABCBF3 63
#
99 Couple Bowl
0
hohowan
0 00ABCBF4 63
#
99 Bear
0
hohowan
0 00ABCBF5 63
#
99 Bezeliel Toothbrush
0
hohowan
0 00ABCBF6 63
#
99 Cannon de Kanon
0
hohowan
0 00ABCBF7 63
#
99 Tokikagura's Magatama
0
hohowan
0 00ABCBF8 63
#
99 Tentouki's Mirror
0
hohowan
0 00ABCBF9 63
#
99 Superalloy Avatar
0
hohowan
0 00ABCBFA 63
#
99 Great-Grandson Hand
0
hohowan
0 00ABCBFB 63
#
99 Ripple Cream
0
hohowan
0 00ABCBFC 63
#
99 Hammer Charge
0
hohowan
0 00ABCBFD 63
#
99 Rupianes Crystal
0
hohowan
0 00ABCBFE 63
#
99 Smart Belt
0
hohowan
0 00ABCBFF 63
#
99 Infinity Glass
0
hohowan
0 00ABCC00 63
#
99 Dianthus Necklace
0
hohowan
0 00ABCC01 63
#
99 Genelotic Ticket
0
hohowan
0 00ABCC02 63
#
99 Tenryo Nyuroki
0
hohowan
0 00ABCC03 63
#
99 G.Falkes Mask
0
hohowan
0 00ABCC04 63
#
99 Manaf Crystal Ball
0
hohowan
0 00ABCC05 63
#
99 Felionyuroki
0
hohowan
0 00ABCC06 63
#
99 Quatanyuroki
0
hohowan
0 00ABCC07 63
#
99 Pheynyuroki
0
hohowan
0 00ABCC08 63
#
99 Pikari Ore
0
hohowan
0 00ABCC09 63
#
99 Formium Material
0
hohowan
0 00ABCC0A 63
#
99 Jewelry Beads
0
hohowan
0 00ABCC0B 63
#
99 Conductorium
0
hohowan
0 00ABCC0C 63
#
99 Luxury Balm
0
hohowan
0 00ABCC0D 63
#
99 Quantavia Fabric
0
hohowan
0 00ABCC0E 63
#
99 Zenpretelecard
0
hohowan
0 00ABCC0F 63
#
99 Monthly Teen Jewel
0
hohowan
0 00ABCC10 63
#
99 Passion Pulp
0
hohowan
0 00ABCC11 63
#
99 Honokano Nyuroki
0
hohowan
0 00ABCC17 63
#
99 Felion Garland
0
hohowan
0 00ABCC2C 63
#
99 Weakness Sign
0
hohowan
0 00ABCC31 63
#
99 TC21 58-Electrode Tube
0
hohowan
0 00ABCC60 63
#
99 Power Splitter
0
hohowan
0 00ABCC61 63
#
99 Flat Resin Board
0
hohowan
0 00ABCC62 63
#
99 Power Sonic 100
0
hohowan
0 00ABCC63 63
#
99 Power Sonic 500
0
hohowan
0 00ABCC64 63
#
99 Anti-Friction Gear
0
hohowan
0 00ABCC65 63
#
99 Disk Ram
0
hohowan
0 00ABCC66 63
#
99 Burst Hardening Gel
0
hohowan
0 00ABCC67 63
#
99 DDW Density Sensor
0
hohowan
0 00ABCC68 63
#
99 Legendary Screw
0
hohowan
0 00ABCC69 63
#
99 Portable Cycloton
0
hohowan
0 00ABCC6A 63
#
99 Marugame Brand Wire
0
hohowan
0 00ABCC6B 63
#
99 Placenta Special
0
hohowan
0 00ABCC12 63
#
99 Lucky Outs
0
hohowan
0 00ABCC13 63
#
99 Furonaga's Ambition
0
hohowan
0 00ABCC14 63
#
99 Allyl Tear
0
hohowan
0 00ABCC15 63
#
99 Silent Green
0
hohowan
0 00ABCC16 63
#
99 Bezeliel Crystal
0
hohowan
0 00ABCC18 63
#
99 Honokano Dumplings
0
hohowan
0 00ABCC19 63
#
99 Distilline
0
hohowan
0 00ABCC1A 63
#
99 Tattorian Z
0
hohowan
0 00ABCC1B 63
#
99 Thick Hotspring Powder
0
hohowan
0 00ABCC1C 63
#
99 Star Emperor Gria
0
hohowan
0 00ABCC1D 63
#
99 Freeze-Dried Powder
0
hohowan
0 00ABCC1E 63
#
99 Tatoriano ZZ
0
hohowan
0 00ABCC1F 63
#
99 Basmoothie
0
hohowan
0 00ABCC20 63
#
99 Phage Predator Team
0
hohowan
0 00ABCC21 63
#
99 Sharly Beans
0
hohowan
0 00ABCC22 63
#
99 Genius Red Soup
0
hohowan
0 00ABCC23 63
#
99 Stealth Relief Drink
0
hohowan
0 00ABCC24 63
#
99 The Joy of Wounding
0
hohowan
0 00ABCC26 63
#
99 Singing Miracle of Love
0
hohowan
0 00ABCC27 63
#
99 Supreme Children's Energy Source
0
hohowan
0 00ABCC28 63
#
99 Creeping Sham Flour
0
hohowan
0 00ABCC29 63
#
99 Harmonian Aroma
0
hohowan
0 00ABCC2A 63
#
99 HUG me Honey!
0
hohowan
0 00ABCC2B 63
#
99 Synapse Grass Seeds
0
hohowan
0 00ABCC2D 63
#
99 Felie's Elixir
0
hohowan
0 00ABCC2E 63
#
99 Snow of Amnesia
0
hohowan
0 00ABCC2F 63
#
99 Amber Imprison
0
hohowan
0 00ABCC30 63
#
99 Lotus Tear
0
hohowan
0 00ABCC32 63
#
99 Honokano Spring Powder
0
hohowan
0 00ABCC33 63
#
99 Ribden Dioxide
0
hohowan
0 00ABCC34 63
#
99 Particle Consolidation Spray
0
hohowan
0 00ABCC35 63
#
99 Song Stone Crystal
0
hohowan
0 00ABCC36 63
#
99 Time Grass
0
hohowan
0 00ABCC37 63
#
99 Multicolor Flower
0
hohowan
0 00ABCC38 63
#
99 Pita-Ban
0
hohowan
0 00ABCC39 63
#
99 Yellow Supplement
0
hohowan
0 00ABCC3A 63
#
99 Green Supplement
0
hohowan
0 00ABCC3B 63
#
99 Red Supplement
0
hohowan
0 00ABCC3C 63
#
99 Let's Fight V
0
hohowan
0 00ABCC3D 63
#
99 Re-Bye-Bye Mask
0
hohowan
0 00ABCC3F 63
#
99 Handmade Muffler
0
hohowan
0 00ABCC40 63
#
99 Pepen @ Mark
0
hohowan
0 00ABCC41 63
#
99 Ra Ziela
0
hohowan
0 00ABCC42 63
#
99 Quantum Satellite Spinner
0
hohowan
0 00ABCC43 63
#
99 Wave Dimension Converter
0
hohowan
0 00ABCC44 63
#
99 Decoherence Lottery
0
hohowan
0 00ABCC45 63
#
99 IAQL Ionization Umbrella
0
hohowan
0 00ABCC46 63
#
99 Superconductor Dendrobium
0
hohowan
0 00ABCC47 63
#
99 Intrinsic Tube
0
hohowan
0 00ABCC48 63
#
99 Unopenable Nyurokey
0
hohowan
0 00ABCC49 63
#
99 Charming Chatter
0
hohowan
0 00ABCC4A 63
#
99 Geno-Wave Gear
0
hohowan
0 00ABCC4B 63
#
99 Satellite Launcher
0
hohowan
0 00ABCC4C 63
#
99 Ai & Sho Oracle
0
hohowan
0 00ABCC4D 63
#
99 Memory Unlocker
0
hohowan
0 00ABCC4E 63
#
99 Genetically Modified Wire
0
hohowan
0 00ABCC4F 63
#
99 Mr. Registrar
0
hohowan
0 00ABCC50 63
#
99 Helicalusion
0
hohowan
0 00ABCC51 63
#
99 Shocking Cart
0
hohowan
0 00ABCC52 63
#
99 Trinity Burner
0
hohowan
0 00ABCC53 63
#
99 Michine Gun
0
hohowan
0 00ABCC54 63
#
99 Resetta Stone
0
hohowan
0 00ABCC55 63
#
99 HD Compiler
0
hohowan
0 00ABCC56 63
#
99 One of a Millionth Soreil
0
hohowan
0 00ABCC57 63
#
99 Pendulum of Rupiah
0
hohowan
0 00ABCC58 63
#
99 S2 Missile Fireworks
0
hohowan
0 00ABCC59 63
#
99 Gravitation Drive Communicator
0
hohowan
0 00ABCC5A 63
#
99 Primnotron
0
hohowan
0 00ABCC5B 63
#
99 Ar noSurge Tube LE
0
hohowan
0 00ABCC5C 63
#
99 Uukun Puppet
0
hohowan
0 00ABCC5D 63
#
99 Ra-Ciel Factor
0
hohowan
0 00ABCC5E 63
#
99 Reincarnation
0
hohowan
0 00ABCC5F 63
#
99 Cream Cathoda
0
hohowan
0 00ABCC6C 63
#
99 Wrinkle Emperor Pipe
0
hohowan
0 00ABCC6D 63
#
99 Lyrical Hitman
0
hohowan
0 00ABCC6E 63
#
99 Sham Croquette Device
0
hohowan
0 00ABCC6F 63
#
99 Heavenly Bird Dance
0
hohowan
0 00ABCC70 63
#
99 Chunpiece
0
hohowan
0 00ABCC71 63
#
99 Glass Change Pack
0
hohowan
0 00ABCC72 63
#
99 Woodpecker Chun
0
hohowan
0 00ABCC73 63
#
99 Celebrity Device
0
hohowan
0 00ABCC74 63
#
99 Pile Drive Device
0
hohowan
0 00ABCC75 63
#
99 Radium Device
0
hohowan
0 00ABCC76 63
#
99 Seven Spice Device
0
hohowan
0 00ABCC77 63
#
99 Nitro Booster Device
0
hohowan
0 00ABCC78 63
#
99 Excalibur Device
0
hohowan
0 00ABCC79 63
#
99 Motoko Aino's Love Theory
0
hohowan
0 00ABCC7A 63
#
99 DIY Device
0
hohowan
0 00ABCC7B 63
#
99 Super Painful Cathode
0
hohowan
0 00ABCC7C 63
#
99 Brain Synapsis
0
hohowan
0 00ABCC7D 63
#
99 Entanglement Device
0
hohowan
0 00ABCC7E 63
#
99 Colonia Cathode
0
hohowan
0 00ABCC7F 63
#
99 Machorino
0
hohowan
0 00ABCC80 63
#
99 Linking Mysterious Ice
0
hohowan
0 00ABCC81 63
#
99 Loving Liposome
0
hohowan
0 00ABCC82 63
#
99 Genonuman Bun
0
hohowan
0 00ABCC83 63
#
99 Felionia RNA
0
hohowan
0 00ABCC84 63
#
99 Cielnotronica
0
hohowan
0 00ABCC85 63
#
99 Sandalbird
0
hohowan
0 00ABCC86 63
#
99 Moisturizer
0
hohowan
0 00ABCC87 63
#
99 MeasuRNA
0
hohowan
0 00ABCC88 63
#
99 Cuticlear
0
hohowan
0 00ABCC89 63
#
99 Giga Protein
0
hohowan
0 00ABCC8A 63
#
99 Cell Protecta
0
hohowan
0 00ABCC8B 63
#
99 Neregracos Scale
0
hohowan
0 00ABCC8C 63
#
99 Mollusc Body
0
hohowan
0 00ABCC8D 63
#
99 Zombiliambskin
0
hohowan
0 00ABCC8E 63
#
99 Petier Cooler
0
hohowan
0 00ABCC8F 63
#
99 EMURNA
0
hohowan
0 00ABCC90 63
#
99 Iron Mask Super Transformer
0
hohowan
0 00ABCC91 63
#
99 Amoeva RNA
0
hohowan
0 00ABCC92 63
#
99 Ectoplasman
0
hohowan
0 00ABCC93 63
#
99 Jelly Type Class
0
hohowan
0 00ABCC94 63
#
99 Silent Picture Scrool
0
hohowan
0 00ABCC95 63
#
99 Underwater Ring-Toss Class
0
hohowan
0 00ABCC96 63
#
99 Aquarium Light
0
hohowan
0 00ABCC97 63
#
99 Nay's Charm
0
hohowan
0 00ABCC98 63
#
99 Carefree Class
0
hohowan
0 00ABCC99 63
#
99 Melancholy of the Genom King
0
hohowan
0 00ABCC9A 63
#
99 Arbitrator's Memorization Note
0
hohowan
0 00ABCC9B 63
#
99 Classy Dance Class
0
hohowan
0 00ABCC9C 63
#
99 Spherial Class
0
hohowan
0 00ABCC9D 63
#
99 Natural Herb Class
0
hohowan
0 00ABCC9E 63
#
99 Organic Brain
0
hohowan
0 00ABCC9F 63
#
99 Gigabolt Neuron
0
hohowan
0 00ABCCA0 63
#
99 Peace Marclass
0
hohowan
0 00ABCCA1 63
#
99 Heaven Sense Class
0
hohowan
0 00ABCCA2 63
#
99 Memory Leap
0
hohowan
0 00ABCCA3 63
#
99 Tube of Strong Interaction
0
hohowan
0 00ABCCA4 63
#
99 Chikichiki Ponpon
0
hohowan
0 00ABCCA5 63
#
99 Loverator Class
0
hohowan
0 00ABCCA6 63
#
99 DHW Drone
0
hohowan
0 00ABCCA7 63
#
99 Simple Cathode
0
hohowan
0 00ABCCA8 63
#
99 Powered Plug Device
0
hohowan
0 00ABCCA9 63
#
99 Hydro Flask Device
0
hohowan
0 00ABCCAA 63
#
99 Bezeliation Device
0
hohowan
0 00ABCCAB 63
#
99 Pure High Tech RNA
0
hohowan
0 00ABCCAC 63
#
99 Bioroid RNA
0
hohowan
0 00ABCCAD 63
#
99 Antiparticle Burst RNA
0
hohowan
0 00ABCCAE 63
#
99 Hymmnes RNA
0
hohowan
0 00ABCCAF 63
#
99 Inception Class
0
hohowan
0 00ABCCB0 63
#
99 Advanced Class
0
hohowan
0 00ABCCB1 63
#
99 Placentia Class
0
hohowan
0 00ABCCB2 63
#
99 Surge Link Class
0
hohowan
0 00ABCCB3 63
#
Max Money (CT)
0
JorgeFFC
0 00B0B82C 3B9AC9FF
#
Max Dive Points
0
JorgeFFC
0 00B13EC8 3B9AC9FF
0 00B13ECC 3B9AC9FF
/*
First line is for Delta.
Second line is for Earthes.
Does not work inside Dive
Machine, only with Triangle
Menu Opened.
*/
#
Max Money on Buy
0
JorgeFFC
0 002CF908 40810008
#
Max Items On Change
0
JorgeFFC
0 002C9370 40810014
#
Overpower Burst Charge (Max Power of Song Special)
0
JorgeFFC
0 0006E960 40810008
#
Infinite Strikes In Battles (All Attacks)
0
JorgeFFC
0 0006BF94 30630000
0 0006BFA4 30630000
0 0006BFB4 30630000
0 0006BFC4 30630000
#
AoB Max Money on Buy
0
JorgeFFC
B 00010000 04000000
B 80A3B82C7C0520004181000860A4000038A00000 80A3B82C7C0520004081000860A4000038A00000
#
AoB Max Items On Change
0
JorgeFFC
B 00010000 04000000
B 2C050063418100142C05000040800008 2C050063408100142C05000040800008
#
AoB Overpower Burst Charge (Max Power of Song Special)
0
JorgeFFC
B 00010000 04000000
B 7CC620147C0628004181000860C50000 7CC620147C0628004081000860C50000
#
AoB Infinite Strikes In Battles (All Attacks)
0
JorgeFFC
B 00010000 04000000
B 807E00103063FFFF907E001048000030807E00183063FFFF907E001848000020807E00283063FFFF907E002848000010807E00203063FFFF 807E001030630000907E001048000030807E001830630000907E001848000020807E002830630000907E002848000010807E002030630000
#