Inf. Items in Battle(Do not use together with inf outside battles)
0
0 002506BC 60000000
#
Inf. Items Outside Battle or in Maps
0
0 00289FE0 60000000
#
Never consume any material on synthesis
0
0 002405BC 7D054378
#
Freeze Days(Don't spend days in nothing, use after day 4-1)
0
0 002A99F0 7CC53378
#
Max Effect on Synthesis Results(Crafted Items and Equipment)
0
0 002BC75C D3DC0004
#
Nothing Consume any MP
0
0 0012B054 60000000
#
Always have Field Event Gauge Filled(After 1 Battle)
0
0 0022DED0 7D064378
#
Don't Decrease Support Gauge(Doesn't work if it's a monster reducing morale)
0
0 0010FB4C 7C641B78
#
Support Gauge Always Maxed
0
0 00120E68 38A00384
#
Synthesis Property Points always 50
0
0 002D3BA8 38800032
#
