Also known as
Resident Evil Code Veronica X

#
Always Low Time
0
CodeFreak/PS3UserCheat
0 00BB3E38 00000000
#
Retry Always 0
0
CodeFreak/PS3UserCheat
0 00BB3E40 00000000
#
No Save Record
0
CodeFreak/PS3UserCheat
0 00BB3618 00000000
#
Infinite Health
0
CodeFreak/PS3UserCheat
0 00BDEA9E 00C8
#
Unlock Everything
0
CodeFreak/PS3UserCheat
0 00BB358C 00001FFF
#
Unlock All Files
0
CodeFreak/PS3UserCheat
0 00BB3E04 00FFFFFF
#
1st Person View
0
CodeFreak/PS3UserCheat
0 00BB35F7 12
#
Normal View
0
CodeFreak/PS3UserCheat
0 00BB35F7 C2
#
Special Weapon in Item Box
0
CodeFreak/PS3UserCheat
0 00BB3AE4 002003E7
0 00BB3AE8 00020BB5
0 00BB3AEC 000303E7
0 00BB3AF0 000403E7
0 00BB3AF4 002103E7
0 00BB3AF8 00220F9C
0 00BB3AFC 008E03E7
0 00BB3B00 000B03E7
0 00BB3B04 000103E7
#
Save Free Near Typewriter
0
CodeFreak/PS3UserCheat
0 00BB35FD 20
#
Item Box Anywhere
0
CodeFreak/PS3UserCheat
0 00BB35FD 04
#
Security Box 1 Anywhere
0
CodeFreak/PS3UserCheat
0 00BB35FD 0C
#
Security Box 2 Anywhere
0
CodeFreak/PS3UserCheat
0 00BB35FD 14
#