Dumb Opponents 1
0
0 008D8DB0 00000000
This can be useful for road rage or marked man because opponents
drive in circles backing up and and moving forward like they can
not figure out how to drive.
#
Dumb Opponents 2
0
0 008D8DB4 00000000
This causes opponents to lose control if you are near them. At
the beginning of a race opponents will not move, but if you get far
enough away they will, and when they catch up whatever they are
doing they will keep doing, so if they are driving forward in a
straight line they will do that until they hit a wall. If they were
turning they will drive in circles. In Road Rage this is not useful
because opponents will drive straight into walls and crash themselves.
#
Unlimited Lives In Marked Man + Road Rage
0
0 00126FBC 39200000
In road rage it will still tell you to repair your car, but
it affects nothing, you can still wreck your car 100
consecutive times and never lose the event.
#
Boost Never Decreases
0
0 000C094C C0030098
You will need to get some boost first. If you crash and lose
boost, you lose boost.
#
9999 Road Rage Takedowns
0
0 00127320 3960270E
#
Each Takedown In Road Rage Is 10 Takedowns
0
0 00127328 396B000A
#
9999 Consecutive Road Rage Takedowns
0
0 00172794 3960270E
#
Each Takedown In Road Rage Is 10 Consecutive Takedowns
0
0 0017279C 396B000A
#
1000x Stunt Score Multiplier
0
0 00107B98 39002710
The game will not show it, but it works.
#
999,999 Stunt Score
0
0 00107BBC 3D40000F
0 00107BC0 614A423F
Do any stunt and you will have that score.
#
Every Stunt Is Worth 999,999 Amount
0
0 00107BB4 3C00000F
0 00107BB8 6000423F
#
0.9375x Speed Modifier For Everything
0
0 008D3E48 3F700000
#
0.875x Speed Modifier For Everything
0
0 008D3E48 3F600000
#
0.8125x Speed Modifier For Everything
0
0 008D3E48 3F500000
#
0.75x Speed Modifier For Everything
0
0 008D3E48 3F400000
#
0.6875x Speed Modifier For Everything
0
0 008D3E48 3F300000
#
0.625x Speed Modifier For Everything
0
0 008D3E48 3F200000
#
0.5625x Speed Modifier For Everything
0
0 008D3E48 3F100000
#
0.5x Speed Modifier For Everything
0
0 008D3E48 3F000000
#
