Max Souls
0
Medo, Skiller
0 00AF0FC4 3D403E80
#
Damage (Player + Enemy)
0
Medo
0 0199C790 60000000
0 0199C79C 60000000
#
Max Equipment Load
0
Medo
0 0199C71C 49499000
#
Max Stats
0
Medo
0 0199C76C 49000000
#
Max Items on Use + Discard + Buy + Deposit in Storage
0
Medo
0 00BC3A68 60000000
#
Infinite Magic + Miracles + Pyromancy Slot #1
0
Medo
0 00BCC2B4 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot #2
0
Medo
0 00BCC2F4 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot #3
0
Medo
0 00BCC334 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot #4
0
Medo
0 00BCC374 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot #5
0
Medo
0 00BCC3B4 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot #6
0
Medo
0 00BCC3F4 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot #7
0
Medo
0 00BCC434 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot #8
0
Medo
0 00BCC474 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot #9
0
Medo
0 00BCC4B4 30A90004
#
Infinite Magic + Miracles + Pyromancy Slot #10
0
Medo
0 00BCC4F4 30A90004
#
Fly Mode (Useless)
0
Medo
0 0199B188 34000001
#