Money Max
0
CodeFreak/PS3UserCheat
0 4257A004 3B9AC9FF
#
Play Day 1
0
CodeFreak/PS3UserCheat
0 4257A00C 00000001
#
A-SPEC EXP Max
0
CodeFreak/PS3UserCheat
0 4257FCFC 05F5E0FF
/*
Should use separately.
Complete one of A Licenses
or win one. Race of B
License to Reach LV 40.
*/
#
B-SPEC EXP Max
0
CodeFreak/PS3UserCheat
0 4257FD04 05F5E0FF
/*
Should use separately.
Complete one of A Licenses
or win one. Race of B
License to Reach LV 40.
*/
#