Infinite Gil (Activate but Stops Earning Money as side-effect)
0
0 0064ED44 7D034378
#
Infinite Gil (Deactivate and Fix Earning Money side-effect)
0
0 0064ED44 7C681814
#
Gil Reward Multiplier x2
0
0 00105AE0 1F440002
#
Gil Reward Multiplier x4
0
0 00105AE0 1F440004
#
Gil Reward Multiplier x8
0
0 00105AE0 1F440008
#
Gil Reward Multiplier x50
0
0 00105AE0 1F440032
#
Deactivate Gil Reward Multipliers
0
0 00105AE0 7C9A07B4
#
Infinite Dash Gauge
0
0 00227BA8 D0440014
#
Deactivate Infinite Dash Gauge
0
0 00227BA8 D0240014
#
Time Doesn't Decrease
0
0 00237938 7C9F2378
/*It has a side-effect.
Some quests have a right
time to do them. You have
to deactivate it to go on
through the game. If you
make an event that
advances time, you will
probably be stuck on the
winning screen after any
battle if you don't
deactivate the code.*/
#
Deactivate Time Doesn't Decrease
0
0 00237938 7FE43014
#
Invincibile + Can Use Magic
0
0 00115678 807E0030
#
Deactivate Invincibile + Can Use Magic
0
0 00115678 807E0030
#
Infinite GP
0
0 0064EFB8 912828E8
#
Deactivate Infinite GP
0
0 0064EFB8 906828E8
#
Enemy Freezes Move
0
0 000F041C 40800028
#
Deactivate Enemy Freezes Move
0
0 000F041C 41800028
#
Damage Multiplier 150%
0
0 0013E7B0 3F000000
#
Damage Multiplier 200%
0
0 0013E7B0 3F800000
#
Deactivate Damage Multiplier
0
0 0013E7B0 3C23D70A
#
