Camouflage 100%
0
0 005C2FFC 2C0603E8
0 005C3004 38C003E8
/*
For MGS: Peace Walker HD
*/
#
Alert Disable
0
0 006FBFDF 40
/*
For MGS 3: Snake Eater HD
*/
#
No Hit Fire
0
0 011D0B54 00000000
/*
For MGS 3: Snake Eater HD
*/
#
No Enemy Mode
0
0 005CBC11 40
/*
For MGS 2: Sons Of
Liberty HD
*/
#
Rapid Fire
0
0 00802F9C 00
/*
For MGS 2: Sons Of
Liberty HD
*/
#
Alert Disable
0
0 005481E3 40
/*
For MGS 2: Sons Of
Liberty HD
*/
#
Invincible Mode
0
0 0080B38B 00
/*
For MGS 2: Sons Of
Liberty HD
*/
#
