Also known as
Ni No Kuni Wrath Of The White Witch

#
Level Up on Every Battle
0
vosman
0 3121B7A4 007FFF3C
#
Infinite Health
0
vosman
0 3121B7A8 007FFF3C
#
Infinite Magic
0
vosman
0 3121B7AC 007FFF3C
#
Max Health
0
vosman
0 3121B7B8 007FFF3C
#
Max Magic
0
vosman
0 3121B7BC 007FFF3C
#
Damage Player + Enemy
0
xtatu
0 005FC3C4 4086EC98
#
Max HP + MP Summon
0
Medo
0 3121B7D8 000003E7
0 3121B7DC 000003E7
#