Also known as
Biohazard Code Veronica X

#
Always Low Time
0
CodeFreak/PS3UserCheat
0 00BB3DB8 00000000
#
Retry Always 0
0
CodeFreak/PS3UserCheat
0 00BB3DC0 00000000
#
No Save Record
0
CodeFreak/PS3UserCheat
0 00BB3598 00000000
#
Infinite Health
0
CodeFreak/PS3UserCheat
0 00BDEA1E 00C8
#
Unlock Everything
0
CodeFreak/PS3UserCheat
0 00BB350C 00001FFF
#
Unlock All Files
0
CodeFreak/PS3UserCheat
0 00BB3D84 00FFFFFF
#
1st Person View
0
CodeFreak/PS3UserCheat
0 00BB3577 C2
#
Normal View
0
CodeFreak/PS3UserCheat
0 00BB3577 12
#
Get Special Weapon in Item Box
0
CodeFreak/PS3UserCheat
0 00BB3A68 00020BB5
0 00BB3A6C 000303E7
0 00BB3A70 000403E7
0 00BB3A74 002103E7
0 00BB3A78 00220F9C
0 00BB3A7C 008E03E7
0 00BB3A80 000B03E7
0 00BB3A84 000103E7
#
Save Free Near Typewriter
0
CodeFreak/PS3UserCheat
0 00BB357D 20
#
Item Box Anywhere
0
CodeFreak/PS3UserCheat
0 00BB357D 04
#
Security Box 1 Anywhere
0
CodeFreak/PS3UserCheat
0 00BB357D 0C
#
Security Box 2 Anywhere
0
CodeFreak/PS3UserCheat
0 00BB357D 14
#