[ICO] Enemy 1 Hit Kill
0
0 0012CF5C 60000000
/*
Don't use cheats for
both games at the same
time.
*/
#
[ICO] Enemy Low AI
0
0 001328FC 60000000
/*
Don't use cheats for
both games at the same
time.
*/
#
[SotC] Unlock Hard Mode after Saving
0
0 014DBB6C 00000001
/*
Don't use cheats for
both games at the same
time.
*/
#
[SotC] Infinite Health
0
0 014DFA40 43C80000
6 007103EC 0000002C
0 00000000 43C80000
/*
Don't use cheats for
both games at the same
time.
*/
#
[SotC] Infinite Grip
0
0 014DFA44 43480000
6 007103EC 00000030
0 00000000 43480000
/*
Don't use cheats for
both games at the same
time.
*/
#
[SotC] Attack Max
0
0 014DF9E0 43C80000
/*
Don't use cheats for
both games at the same
time.
*/
#
