clean:
	rm -f *.o *.elf *.map *.bin payload_src/*.o lv2/src/*.o
all:
	make -f Makefile_3.55 clean --no-print-directory
	make -f Makefile_3.55 --no-print-directory
	make -f Makefile_3.55D clean --no-print-directory
	make -f Makefile_3.55D --no-print-directory
	make -f Makefile_4.21 clean --no-print-directory
	make -f Makefile_4.21 --no-print-directory
	make -f Makefile_4.21D clean --no-print-directory
	make -f Makefile_4.21D --no-print-directory
	make -f Makefile_4.30 clean --no-print-directory
	make -f Makefile_4.30 --no-print-directory
	make -f Makefile_4.30D clean --no-print-directory
	make -f Makefile_4.30D --no-print-directory
	make -f Makefile_4.31 clean --no-print-directory
	make -f Makefile_4.31 --no-print-directory
	make -f Makefile_4.40 clean --no-print-directory
	make -f Makefile_4.40 --no-print-directory
	make -f Makefile_4.41 clean --no-print-directory
	make -f Makefile_4.41 --no-print-directory
	make -f Makefile_4.41D clean --no-print-directory
	make -f Makefile_4.41D --no-print-directory
	make -f Makefile_4.46 clean --no-print-directory
	make -f Makefile_4.46 --no-print-directory
	make -f Makefile_4.46D clean --no-print-directory
	make -f Makefile_4.46D --no-print-directory
	make -f Makefile_4.50 clean --no-print-directory
	make -f Makefile_4.50 --no-print-directory
	make -f Makefile_4.50D clean --no-print-directory
	make -f Makefile_4.50D --no-print-directory
	make -f Makefile_4.53 clean --no-print-directory
	make -f Makefile_4.53 --no-print-directory
	make -f Makefile_4.53D clean --no-print-directory
	make -f Makefile_4.53D --no-print-directory
	make -f Makefile_4.55 clean --no-print-directory
	make -f Makefile_4.55 --no-print-directory
	make -f Makefile_4.55D clean --no-print-directory
	make -f Makefile_4.55D --no-print-directory
	make -f Makefile_4.60 clean --no-print-directory
	make -f Makefile_4.60 --no-print-directory
	make -f Makefile_4.60D clean --no-print-directory
	make -f Makefile_4.60D --no-print-directory
	make -f Makefile_4.65 clean --no-print-directory
	make -f Makefile_4.65 --no-print-directory
	make -f Makefile_4.65D clean --no-print-directory
	make -f Makefile_4.65D --no-print-directory
	make -f Makefile_4.66 clean --no-print-directory
	make -f Makefile_4.66 --no-print-directory
	make -f Makefile_4.66D clean --no-print-directory
	make -f Makefile_4.66D --no-print-directory
	make -f Makefile_4.70 clean --no-print-directory
	make -f Makefile_4.70 --no-print-directory
	make -f Makefile_4.70D clean --no-print-directory
	make -f Makefile_4.70D --no-print-directory
	make -f Makefile_4.75 clean --no-print-directory
	make -f Makefile_4.75 --no-print-directory
	make -f Makefile_4.75D clean --no-print-directory
	make -f Makefile_4.75D --no-print-directory
	make -f Makefile_4.76 clean --no-print-directory
	make -f Makefile_4.76 --no-print-directory
	make -f Makefile_4.76D clean --no-print-directory
	make -f Makefile_4.76D --no-print-directory
	make -f Makefile_4.78 clean --no-print-directory
	make -f Makefile_4.78 --no-print-directory
	make -f Makefile_4.78D clean --no-print-directory
	make -f Makefile_4.78D --no-print-directory
	make -f Makefile_4.80 clean --no-print-directory
	make -f Makefile_4.80 --no-print-directory
	make -f Makefile_4.80D clean --no-print-directory
	make -f Makefile_4.80D --no-print-directory
	make -f Makefile_4.80E clean --no-print-directory
	make -f Makefile_4.80E --no-print-directory
	make -f Makefile_4.81 clean --no-print-directory
	make -f Makefile_4.81 --no-print-directory
	make -f Makefile_4.81D clean --no-print-directory
	make -f Makefile_4.81D --no-print-directory
	make -f Makefile_4.81E clean --no-print-directory
	make -f Makefile_4.81E --no-print-directory
	make -f Makefile_4.82 clean --no-print-directory
	make -f Makefile_4.82 --no-print-directory
	make -f Makefile_4.82D clean --no-print-directory
	make -f Makefile_4.82D --no-print-directory
	make -f Makefile_4.82E clean --no-print-directory
	make -f Makefile_4.82E --no-print-directory
	make -f Makefile_4.83 clean --no-print-directory
	make -f Makefile_4.83 --no-print-directory
	make -f Makefile_4.83D clean --no-print-directory
	make -f Makefile_4.83D --no-print-directory
	make -f Makefile_4.83E clean --no-print-directory
	make -f Makefile_4.83E --no-print-directory
	make -f Makefile_4.84 clean --no-print-directory
	make -f Makefile_4.84 --no-print-directory
	make -f Makefile_4.84D clean --no-print-directory
	make -f Makefile_4.84D --no-print-directory
	make -f Makefile_4.84E clean --no-print-directory
	make -f Makefile_4.84E --no-print-directory
	rm -f *.o *.elf *.map source/*.o lv2/src/*.o
