Always 1st + Max Fire
0
jgduff
0 009618E0 92A90070
#
Damage Never Decreases
0
jgduff
0 00171154 907F047C
/*
Deactivate it for Boss
Races.
*/
#
Lot Of Fans On Start Race + Max Rank + Unlock All Vehicles
0
jgduff
0 00181F3C 909F0004 
/*
Does not work in
Destruction Races.
*/
#
Max Points + Max Fires On 1 Hit (Destruction Race)
0
jgduff
0 00AFF9EC 905F0104 
#
Points x11 + Easy Max Fires (Destruction Race)
0
jgduff
0 00AFF9E8 7E86DA14 
#
Infinite Time On Checkpoint Race
0
jgduff
0 00AFD438 60000000 
#
Infinite Fans Stunt Time
0
jgduff
0 00193378 60000000 
#