File Info
0
bungholio
/*
BLES01161 & BLUS30510
are nearly identical,
there are just a few
strings of slightly
different dates and time
stamps, and 1 random tiny
string of bytes somewhere
that are all after the
actual game code so they
likely do not affect
anything in any kind of
way and the files can
likely safely be
considered identical.
*/
#
Infinite Health
0
jgduff1
0 006A2F90 D11F0014
#
Infinite Health + One Hit Kill
0
jgduff1
0 006A2F88 60000000
0 006A2F90 D3BF0014
/*
It also affects enemies.
*/
#
Infinite Magic
0
jgduff1
0 006C87D0 60000000
#
Max Money On Gain
0
jgduff1
0 006CA65C 901E0014
#
Max Level + XP On 1 Kill + High HP + MP + Strength + Agility + Stamina + Will Power
0
jgduff1
0 006CAF1C 7CA0F814
0 006CAF24 901E0024
#
Infinite Skills Points
0
jgduff1
0 008E8E64 60000000
0 008E8E68 60000000
0 008E8CD8 60000000
0 008E8CDC 60000000
0 008E8A14 30A30000
0 008E8A7C 309B0000
0 008E8A80 30630000
#
Memory Infinite Items
0
jgduff1
0 38C92CA4 000000D9
#