Money Max
0
0 424FE004 3B9AC9FF
#
Play Day 1
0
0 424FE00C 00000001
#
A-SPEC EXP Max
0
0 42503CFC 05F5E0FF
/*
Should use separately.
Complete one of A Licenses
or win one. Race of B
License to Reach LV 40.
*/
#
B-SPEC EXP Max
0
0 42503D04 05F5E0FF
/*
Should use separately.
Complete one of A Licenses
or win one. Race of B
License to Reach LV 40.
*/
#
Win A Race To Reach Lv 40
0
vosman
0 00B548EC 3C807FFF
#