Memory Infinite Life
0
jgduff1
0 00A6BA08 00000002
#
ASM Life Never Decreases
0
jgduff1
0 00284DD4 38840000
#
Memory Invincible After Dying 1 Time
0
jgduff1
0 37B4597C 40675E0C
#
ASM Invincible After Dying 1 Time
0
jgduff1
0 00285028 60000000
0 00285030 60000000
#
Memory Bonus Point Increase By x1 On Hit (Easy Max x10)
0
jgduff1
0 35EAB378 00000005
#
ASM Bonus Point Increase By x1 On Hit (Easy Max x10)
0
jgduff1
0 002DBBD4 60000000
0 002DBBD8 D37D004C
#
Memory Easy Max Level Of Yang (You Need To Reach Level x1 For Code Work)
0
jgduff1
0 35EF7848 00000001
#
ASM Easy Max Level Of Yang (You Need To Reach Level x1 For Code Work)
0
jgduff1
0 00192D7C 90E30098
/*
It does not work if
Invincibile After Dying 1
Time is on.
*/
#