Memory Max + Infinite Points On Gain
0
jgduff1
0 33E3B0CC 000F423F
#
ASM Max + Infinite Points On Gain
0
jgduff1
0 004AC3D0 905D0000
#
Infinite Ammo
0
jgduff1
0 0049FF24 60000000
#
Infinite Health From Medkits
0
jgduff1
0 002C211C 92830008
/*
On Medkit gain, if you
approach a Ring Of Life,
the health goes back to
normal and you need
another Medkit for
infinite health.
*/
#
Infinite Health
0
jgduff1
0 002CB4EC 7C034850
0 002CB4F4 901D0000
/*
It also affects enemies.
*/
#