Memory Infinite Time
0
jgduff1
0 3512C877 C8
#
ASM Infinite Time
0
jgduff1
0 002E51A8 38090000
/*
Disable for bosses.
*/
#
Memory Infinite Blue Orbs
0
jgduff1
0 3512C86F 63
#
ASM Infinite Blue Orbs
0
jgduff1
0 002E5208 901E001C
#
Memory Infinite Health
0
jgduff1
0 3512D376 0003
0 3512D37E 270F
0 3512D386 270F
0 3512D38E 270F
/*
Do not use constant
write with this, write
all 4 lines once or you
might encounter a bug.
*/
#
ASM Infinite Health
0
jgduff1
0 002E7A94 90290004
/*
Affects Auto C Rank
instead of A Rank.
*/
#
Memory Infinite Boost
0
jgduff1
0 3558DF10 43BE
0 3558DF20 43BE
0 3558DFC4 3F80
#