Infinite Health
0
jgduff1
0 00662668 EC1EF828
#
Infinite Health + Select Refill Health
0
jgduff1
0 00667DA8 EDAD07B2 
0 00667DAC D13E0B48
/*
The bar still decreases
but you will not die.

It partially affects
enemies.
*/
#
Max Exp
0
jgduff1
0 00662568 EC1F0028
#
Max Points
0
jgduff1
0 00222F68 98490000
#
Infinite + Max Rage On 1 Hit
0
jgduff1
0 00662674 FF9F6000
/*
Kill all enemies to end
Fury mode.

Switch to Styx for
far away enemies.
*/
#