Alternative Names
0
PARAM.SFO
/*
Pac-Man And The Ghostly Adventures
Pac-Man Et Les Aventures De Fantômes
Pac-Man Y Las Aventuras Fantasmales
*/
#
Memory Infinite Health
0
jgduff1
0 369E195C 40400000
#
ASM Infinite Health
0
jgduff1
0 0084F534 60000000
#
Memory Infinite Life
0
jgduff1
0 360B6D70 42C60000
#
ASM Infinite Life
0
jgduff1
0 00843DD0 D0660000
#
Memory Have Many Eyes
0
jgduff1
0 392DC068 4479C000
#