999,999,999 Money
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010AF994 3B9AC9FF
#
Time Never Passes
0
nichecode.blog.fc2.com/blog-entry-120.html
0 000493B8 38A00001
#
Date Never Passes
0
nichecode.blog.fc2.com/blog-entry-120.html
0 0004A690 30A500000
#
Money Gained From Battle Multiplier
0
nichecode.blog.fc2.com/blog-entry-120.html
0 00743BCC 1C63Z
[Z]000A=10x;0064=100x;03E8=1,000;2710=10,000x[/Z]
#
Experience Gained From Battle Multiplier (Humans And Persona)
0
nichecode.blog.fc2.com/blog-entry-120.html
0 00743BB4 1C63Z
[Z]000A=10x;0064=100x;03E8=1,000;2710=10,000x[/Z]
#
Experience Gained After Battle Multiplier (P Character Only)
0
nichecode.blog.fc2.com/blog-entry-120.html
0 003F9F74 1F23Z
[Z]000A=10x;0064=100x;03E8=1,000;2710=10,000x[/Z]
#
Experience Gained After Battle Multiplier (Persona Only)
0
nichecode.blog.fc2.com/blog-entry-120.html
0 003F9D30 1F43Z
[Z]000A=10x;0064=100x;03E8=1,000;2710=10,000x[/Z]
#
Pseudo High-Glow Effect
0
nichecode.blog.fc2.com/blog-entry-120.html
0 003F9DB4 7C992378
#
Item Drop 100%
0
nichecode.blog.fc2.com/blog-entry-120.html
0 0025AFE4 60000000
#
Winning Effect Of Victory
0
nichecode.blog.fc2.com/blog-entry-120.html
0 00665D18 38600001
#
Breath Effect Of Victory
0
nichecode.blog.fc2.com/blog-entry-120.html
0 00665D6C 38600001
#
Ammo Never Decreases
0
nichecode.blog.fc2.com/blog-entry-120.html
0 00723E90 38800000
#
Skill 1
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACA90 0000
/*
Check Persona 5
List.docx for digits.
*/
#
Skill 2
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACA92 0000
/*
Check Persona 5
List.docx for digits.
*/
#
Skill 3
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACA94 0000
/*
Check Persona 5
List.docx for digits.
*/
#
Skill 4
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACA96 0000
/*
Check Persona 5
List.docx for digits.
*/
#
Skill 5
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACA98 0000
/*
Check Persona 5
List.docx for digits.
*/
#
Skills 6
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACA9A 0000
/*
Check Persona 5
List.docx for digits.
*/
#
Skills 7
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACA9C 0000
/*
Check Persona 5
List.docx for digits.
*/
#
Skill 8
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACA9E 0000
/*
Check Persona 5
List.docx for digits.
*/
#
1st Person Skill 1
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACD30 0000
/*
Check Persona 5
List.docx for digits.
*/
#
1st Person Skill 2
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACD32 0000
/*
Check Persona 5
List.docx for digits.
*/
#
1st Person Skill 3
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACD34 0000
/*
Check Persona 5
List.docx for digits.
*/
#
1st Person Skill 4
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACD36 0000
/*
Check Persona 5
List.docx for digits.
*/
#
1st Person Skill 5
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACD38 0000
/*
Check Persona 5
List.docx for digits.
*/
#
1st Person Skills 6
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACD3A 0000
/*
Check Persona 5
List.docx for digits.
*/
#
1st Person Skills 7
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACD3C 0000
/*
Check Persona 5
List.docx for digits.
*/
#
1st Person Skill 8
0
nichecode.blog.fc2.com/blog-entry-120.html
0 010ACD3E 0000
/*
Check Persona 5
List.docx for digits.
*/
#
Summon Cost Of Prisoners Roster (Full Devil) 0 Money
0
nichecode.blog.fc2.com/blog-entry-120.html
0 00603C68 3BC00000
#
Human Parameter Multiplier
0
nichecode.blog.fc2.com/blog-entry-120.html
0 001EE628 1C63Z
[Z]000A=10x;0064=100x;03E8=1,000;2710=10,000x[/Z]
#
Co-op Conversation, Determination Of Possession Of Arcanas
0
nichecode.blog.fc2.com/blog-entry-120.html
0 0054BE7C 7F83E378
0 0054C1A0 7FA3EB78
#
P Character Supplement Member Exp Never Decreases
0
nichecode.blog.fc2.com/blog-entry-120.html
0 003F9A7C 60630001
#
Rank 10 Judgement At Persona Imprisonment
0
nichecode.blog.fc2.com/blog-entry-120.html
0 00602FF4 3860000A
#
Finish Watching Any Book Or DVD With 1 Use
0
nichecode.blog.fc2.com/blog-entry-120.html
0 0054CEF0 60000000
0 0054A89C 60000000
#