Version Note
0
EBOOT.BIN
/*
BLES01398 and BLUS30800
are operationally
identical looking, but
the memory codes might
not work with BLUS30800.

I can't confirm it
because I don't own a
copy.
*/
#
Memory Infinite Health
0
jgduff1
0 B229C9A0 00000064
#
ASM Infinite Health
0
jgduff1
0 000E0064 60000000
#
Memory Infinite + Max Gold
0
jgduff1
0 B247CF1C 000003E7
0 B2B040BC 000003E7
#
ASM Infinite + Max Gold
0
jgduff1
0 0007A2E4 903F0024
#