Eboot Info
0
EBOOT.ELF
/*
They are operationally
identical, just a few
tiny differences that
shouldn't prevent
every code that is ever
found from working for
both versions.
*/
#
Memory Infinite Health
0
jgduff1
0 332F680C 0000034E
#
ASM Infinite Health
0
jgduff1
0 000728A4 90BF01AC
/*
It also affects enemies.
*/
#
Memory Invincible
0
jgduff1
0 332F680C 0000034E
#
ASM Invincible
0
jgduff1
0 0022C018 90BC0250
#
Memory Infinite Magic
0
jgduff1
0 332F78E4 42700000
#
ASM Infinite Magic
0
jgduff1
0 0020E0D8 60000000
0 0020E0DC 60000000
#
Memory Max + Infinite Coin
0
jgduff1
0 33960AD0 00000014
#
ASM Max + Infinite Coin
0
jgduff1
0 0023EAA4 38A0270F
0 0023EAA8 90030010
#