Also known as
Tears To Tiara II Haoh No Matsuei

#
Max Money
0
JorgeFFC
0 00BAEE04 3B9AC9FF
#
Hamil HP 5000
0
JorgeFFC
0 00BA8A66 1388
#
Hamil All Stats Maxed
0
JorgeFFC
0 00BA8A6C 270F
0 00BA8A6E 270F
0 00BA8A70 270F
0 00BA8A72 270F
0 00BA8A74 270F
0 00BA8A76 270F
0 00BA8A78 0063
#
Hamil Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8A51 63
#
Hamil Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8A4D 63
#
Tarte HP 5000
0
JorgeFFC
0 00BA8C2E 1388
#
Tarte All Stats Maxed
0
JorgeFFC
0 00BA8C34 270F
0 00BA8C36 270F
0 00BA8C38 270F
0 00BA8C3A 270F
0 00BA8C3C 270F
0 00BA8C3E 270F
0 00BA8C40 0063
#
Tarte Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8C19 63
#
Tarte Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8C15 63
#
Dion HP 5000
0
JorgeFFC
0 00BA8DF6 1388
#
Dion All Stats Maxed
0
JorgeFFC
0 00BA8DFC 270F
0 00BA8DFE 270F
0 00BA8E00 270F
0 00BA8E02 270F
0 00BA8E04 270F
0 00BA8E06 270F
0 00BA8E08 0063
#
Dion Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8DE1 63
#
Dion Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8DDD 63
#
Enneads HP 5000
0
JorgeFFC
0 00BA8EDA 1388
#
Enneads All Stats Maxed
0
JorgeFFC
0 00BA8EE0 270F
0 00BA8EE2 270F
0 00BA8EE4 270F
0 00BA8EE6 270F
0 00BA8EE8 270F
0 00BA8EEA 270F
0 00BA8EEC 0063
#
Enneads Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8EC5 63
#
Enneads Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8EC1 63
#
Monomachus HP 5000
0
JorgeFFC
0 00BA8FBE 1388
#
Monomachus All Stats Maxed
0
JorgeFFC
0 00BA8FC4 270F
0 00BA8FC6 270F
0 00BA8FC8 270F
0 00BA8FCA 270F
0 00BA8FCC 270F
0 00BA8FCE 270F
0 00BA8FD0 0063
#
Monomachus Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8FA9 63
#
Monomachus Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA8FA5 63
#
Charis HP 5000
0
JorgeFFC
0 00BA90A2 1388
#
Charis All Stats Maxed
0
JorgeFFC
0 00BA90A8 270F
0 00BA90AA 270F
0 00BA90AC 270F
0 00BA90AE 270F
0 00BA90B0 270F
0 00BA90B2 270F
0 00BA90B4 0063
#
Charis Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA908D 63
#
Charis Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9089 63
#
Chalcus HP 5000
0
JorgeFFC
0 00BA98A6 1388
#
Chalcus All Stats Maxed
0
JorgeFFC
0 00BA98AC 270F
0 00BA98AE 270F
0 00BA98B0 270F
0 00BA98B2 270F
0 00BA98B4 270F
0 00BA98B6 270F
0 00BA98B8 0063
#
Chalcus Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9891 63
#
Chalcus Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA988D 63
#
Noa The Elephant HP 5000
0
JorgeFFC
0 00BA998A 1388
#
Noa The Elephant All Stats Maxed
0
JorgeFFC
0 00BA9990 270F
0 00BA9992 270F
0 00BA9994 270F
0 00BA9996 270F
0 00BA9998 270F
0 00BA999A 270F
0 00BA999C 0063
#
Noa The Elephant Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9975 63
#
Noa The Elephant Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9971 63
#
Quadriga HP 5000
0
JorgeFFC
0 00BA9A6E 1388
#
Quadriga All Stats Maxed
0
JorgeFFC
0 00BA9A6E 1388
0 00BA9A74 270F
0 00BA9A76 270F
0 00BA9A78 270F
0 00BA9A7A 270F
0 00BA9A7C 270F
0 00BA9A7E 270F
0 00BA9A80 0063
#
Kleito HP 5000
0
JorgeFFC
0 00BA9186 1388
#
Kleito All Stats Maxed
0
JorgeFFC
0 00BA918C 270F
0 00BA918E 270F
0 00BA9190 270F
0 00BA9192 270F
0 00BA9194 270F
0 00BA9196 270F
0 00BA9198 0063
#
Kleito Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9171 63
#
Kleito Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA916D 63
#
Artio HP 5000
0
JorgeFFC
0 00BA926A 1388
#
Artio Max All Stats
0
JorgeFFC
0 00BA9270 270F
0 00BA9272 270F
0 00BA9274 270F
0 00BA9276 270F
0 00BA9278 270F
0 00BA927A 270F
0 00BA927C 0063
#
Artio Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9255 63
#
Artio Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9251 63
#
Mox HP 5000
0
JorgeFFC
0 00BAA18E 1388
#
Mox Max All Stats
0
JorgeFFC
0 00BAA194 270F
0 00BAA196 270F
0 00BAA198 270F
0 00BAA19A 270F
0 00BAA19C 270F
0 00BAA19E 270F
0 00BAA1A0 0063
#
Mox Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BAA179 63
#
Mox Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BAA175 63
#
Elissa HP 5000
0
JorgeFFC
0 00BA934E 1388
#
Elissa All Stats Maxed
0
JorgeFFC
0 00BA9354 270F
0 00BA9356 270F
0 00BA9358 270F
0 00BA935A 270F
0 00BA935C 270F
0 00BA935E 270F
0 00BA9360 0063
#
Elissa Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9339 63
#
Elissa Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9335 63
#
Daphnis HP 5000
0
JorgeFFC
0 00BA9432 1388
#
Daphnis Max All Stats
0
JorgeFFC
0 00BA9438 270F
0 00BA943A 270F
0 00BA943C 270F
0 00BA943E 270F
0 00BA9440 270F
0 00BA9442 270F
0 00BA9444 0063
#
Daphnis Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA941D 63
#
Daphnis Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9419 63
#
Aemelia HP 5000
0
JorgeFFC
0 00BA9516 1388
#
Aemelia Max All Stats
0
JorgeFFC
0 00BA951C 270F
0 00BA951E 270F
0 00BA9520 270F
0 00BA9522 270F
0 00BA9524 270F
0 00BA9526 270F
0 00BA9528 0063
#
Aemelia Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9501 63
#
Aemelia Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA94FD 63
#
Laelius HP 5000
0
JorgeFFC
0 00BA95FA 1388
#
Laelius Max All Stats
0
JorgeFFC
0 00BA9600 270F
0 00BA9602 270F
0 00BA9604 270F
0 00BA9606 270F
0 00BA9608 270F
0 00BA960A 270F
0 00BA960C 0063
#
Laelius Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA95E5 63
#
Laelius Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA95E1 63
#
Aruru HP 5000
0
JorgeFFC
0 00BA9B52 1388
#
Aruru Max All Stats
0
JorgeFFC
0 00BA9B58 270F
0 00BA9B5A 270F
0 00BA9B5C 270F
0 00BA9B5E 270F
0 00BA9B60 270F
0 00BA9B62 270F
0 00BA9B64 0063
#
Aruru Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9B3D 63
#
Aruru Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9B39 63
#
Arawn HP 5000
0
JorgeFFC
0 00BA9C36 1388
#
Arawn Max All Stats
0
JorgeFFC
0 00BA9C3C 270F
0 00BA9C3E 270F
0 00BA9C40 270F
0 00BA9C42 270F
0 00BA9C44 270F
0 00BA9C46 270F
0 00BA9C48 0063
#
Arawn Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9C21 63
#
Arawn Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9C1D 63
#
Riannon HP 5000
0
JorgeFFC
0 00BA9D1A 1388
#
Riannon Max All Stats
0
JorgeFFC
0 00BA9D20 270F
0 00BA9D22 270F
0 00BA9D24 270F
0 00BA9D26 270F
0 00BA9D28 270F
0 00BA9D2A 270F
0 00BA9D2C 0063
#
Riannon Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9D05 63
#
Riannon Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9D01 63
#
Malvy HP 5000
0
JorgeFFC
0 00BA9DFE 1388
#
Malvy Max All Stats
0
JorgeFFC
0 00BA9E04 270F
0 00BA9E06 270F
0 00BA9E08 270F
0 00BA9E0A 270F
0 00BA9E0C 270F
0 00BA9E0E 270F
0 00BA9E10 0063
#
Malvy Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9DE9 63
#
Malvy Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9DE5 63
#
Alisia HP 5000
0
JorgeFFC
0 00BA9EE2 1388
#
Alisia Max All Stats
0
JorgeFFC
0 00BA9EE8 270F
0 00BA9EEA 270F
0 00BA9EEC 270F
0 00BA9EEE 270F
0 00BA9EF0 270F
0 00BA9EF2 270F
0 00BA9EF4 0063
#
Alisia Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9ECD 63
#
Alisia Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9EC9 63
#
Peggy HP 5000
0
JorgeFFC
0 00BA9FC6 1388
#
Peggy Max All Stats
0
JorgeFFC
0 00BA9FCC 270F
0 00BA9FCE 270F
0 00BA9FD0 270F
0 00BA9FD2 270F
0 00BA9FD4 270F
0 00BA9FD6 270F
0 00BA9FD8 0063
#
Peggy Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9FB1 63
#
Peggy Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA9FAD 63
#
Beard HP 5000
0
JorgeFFC
0 00BAA0AA 1388
#
Beard Max All Stats
0
JorgeFFC
0 00BAA0B0 270F
0 00BAA0B2 270F
0 00BAA0B4 270F
0 00BAA0B6 270F
0 00BAA0B8 270F
0 00BAA0BA 270F
0 00BAA0BC 0063
#
Beard Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BAA095 63
#
Beard Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BAA091 63
#
Saul HP 5000
0
JorgeFFC
0 00BA96DE 1388
#
Saul Max All Stats
0
JorgeFFC
0 00BA96E4 270F
0 00BA96E6 270F
0 00BA96E8 270F
0 00BA96EA 270F
0 00BA96EC 270F
0 00BA96EE 270F
0 00BA96F0 0063
#
Saul Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA96C9 63
#
Saul Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BA96C5 63
#
Phaenna HP 5000
0
JorgeFFC
0 00BAA272 1388
#
Phaenna Max All Stats
0
JorgeFFC
0 00BAA278 270F
0 00BAA27A 270F
0 00BAA27C 270F
0 00BAA27E 270F
0 00BAA280 270F
0 00BAA282 270F
0 00BAA284 0063
#
Phaenna Skill Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BAA25D 63
#
Phaenna Exp 99 (1 Exp = 1 Level)
0
JorgeFFC
0 00BAA259 63
#
Have Hermit Shell
0
JorgeFFC
0 00BAEB2F 63
#
Have Scorpion Tail
0
JorgeFFC
0 00BAEB6B 63
#
Have Spring Hare's Ear
0
JorgeFFC
0 00BAEB6F 63
#
Have Garnet
0
JorgeFFC
0 00BAEB7B 63
#
Have Papyrus Page A
0
JorgeFFC
0 00BAEB97 63
#
Have Papyrus Page B
0
JorgeFFC
0 00BAEB9B 63
#
Have Copper Ore
0
JorgeFFC
0 00BAEBA7 63
#
Have Iron Ore
0
JorgeFFC
0 00BAEBAB 63
#
Have Steel ore
0
JorgeFFC
0 00BAEBAF 63
#
Have Damascus Ore
0
JorgeFFC
0 00BAEBB3 63
#
Have Elfin Tear
0
JorgeFFC
0 00BAEBB7 63
#
Have Platinum Ore
0
JorgeFFC
0 00BAEBBB 63
#
Have Spinel
0
JorgeFFC
0 00BAEBBF 63
#
Have Lazurite
0
JorgeFFC
0 00BAEB7F 63
#
Have Valks
0
JorgeFFC
0 00BAEBDF 63
#
Have Cadmia
0
JorgeFFC
0 00BAEBE3 63
#
Have Golden Wheat
0
JorgeFFC
0 00BAEC47 63
#
Have Touchstone Beginner
0
JorgeFFC
0 00BAEC07 63
#
Have Touchstone Intermediate
0
JorgeFFC
0 00BAEC0B 63
#
Have Copper Sword
0
JorgeFFC
0 00BADCD3 63
#
Have Brass Sword
0
JorgeFFC
0 00BADCD7 63
#
Have Crude Sword
0
JorgeFFC
0 00BADCDB 63
#
Have Iron Sword
0
JorgeFFC
0 00BADCDF 63
#
Have Iron Sword +1
0
JorgeFFC
0 00BADCE3 63
#
Have Iron Sword +2
0
JorgeFFC
0 00BADCE7 63
#
Have Steel Sword
0
JorgeFFC
0 00BADCEB 63
#
Have Damascus Sword
0
JorgeFFC
0 00BADCEF 63
#
Have Damascus Sword +1
0
JorgeFFC
0 00BADCF3 63
#
Have Damascus Sword+2
0
JorgeFFC
0 00BADCF7 63
#
Have Platinum Sword
0
JorgeFFC
0 00BADCFB 63
#
Have Elfin Sword
0
JorgeFFC
0 00BADCFF 63
#
Have Elfin Sword+1
0
JorgeFFC
0 00BADD03 63
#
Have Elfin Sword +2
0
JorgeFFC
0 00BADD07 63
#
Have Silver Sword
0
JorgeFFC
0 00BADD0B 63
#
Have Golden Sword
0
JorgeFFC
0 00BADD0F 63
#
Have Golden Sword +1
0
JorgeFFC
0 00BADD13 63
#
Have Golden Sword +2
0
JorgeFFC
0 00BADD17 63
#
Have Amber Gold Sword
0
JorgeFFC
0 00BADD1B 63
#
Have Gladius
0
JorgeFFC
0 00BADD1F 63
#
Have Gladius +1
0
JorgeFFC
0 00BADD23 63
#
Have Gladius +2
0
JorgeFFC
0 00BADD27 63
#
Have Claidheamh Mor
0
JorgeFFC
0 00BADD2B 63
#
Have Claidheamh Mor +1
0
JorgeFFC
0 00BADD2F 63
#
Have Claidheamh Mor +2
0
JorgeFFC
0 00BADD33 63
#
Have Ascalon
0
JorgeFFC
0 00BADD37 63
#
Have Spada Legatos
0
JorgeFFC
0 00BADD3B 63
#
Have Bealgalltach
0
JorgeFFC
0 00BADD3F 63
#
Have Beallgatach +1
0
JorgeFFC
0 00BADD43 63
#
Have Beallgatach +2
0
JorgeFFC
0 00BADD47 63
#
Have Moralltach
0
JorgeFFC
0 00BADD4B 63
#
Have Kaledvouc'h
0
JorgeFFC
0 00BADD4F 63
#
Have Kaledvouc'h +1
0
JorgeFFC
0 00BADD53 63
#
Have Kaledvouc'h +2
0
JorgeFFC
0 00BADD57 63
#
Have Dark Arondight
0
JorgeFFC
0 00BADD5B 63
#
Have Holy Arondight
0
JorgeFFC
0 00BADD5F 63
#
Have Caliburn +2
0
JorgeFFC
0 00BADD63 63
#
Have Caliburn +3
0
JorgeFFC
0 00BADD67 63
#
Have Caliburn +4
0
JorgeFFC
0 00BADD6B 63
#
Have Fragarach
0
JorgeFFC
0 00BADD6F 63
#
Have Hrotti
0
JorgeFFC
0 00BADD73 63
#
Have Sword of Findias
0
JorgeFFC
0 00BADD77 63
#
Have Melqart's Sword
0
JorgeFFC
0 00BADD7B 63
#
Have Melqart's Sword +1
0
JorgeFFC
0 00BADD7F 63
#
Have Melqart's Sword +2
0
JorgeFFC
0 00BADD83 63
#
Have Melqart Sword +3
0
JorgeFFC
0 00BADD87 63
#
Have Melqart Sword +4
0
JorgeFFC
0 00BADD8B 63
#
Have Melqart Sword +5
0
JorgeFFC
0 00BADD8F 63
#
Have Melqart's Holy Sword
0
JorgeFFC
0 00BADD93 63
#
Have Plage Sword
0
JorgeFFC
0 00BADD97 63
#
Have Plague Sword +1
0
JorgeFFC
0 00BADD9B 63
#
Have Plague Sword +2
0
JorgeFFC
0 00BADD9F 63
#
Have Heretic Sword
0
JorgeFFC
0 00BADDA3 63
#
Have Heretic Sword +1
0
JorgeFFC
0 00BADDA7 63
#
Have Massacre
0
JorgeFFC
0 00BADDAB 63
#
Have Massacre +1
0
JorgeFFC
0 00BADDAF 63
#
Have Barca Sword
0
JorgeFFC
0 00BADDB3 63
#
Have Hero-King's Sword
0
JorgeFFC
0 00BADDB7 63
#
Have Copper Greatsword
0
JorgeFFC
0 00BADDC3 63
#
Have Brass Greatsword
0
JorgeFFC
0 00BADDC7 63
#
Have Brass Greatsword +1
0
JorgeFFC
0 00BADDCB 63
#
Have Buster Sword
0
JorgeFFC
0 00BADDCF 63
#
Have Buster Sword +1
0
JorgeFFC
0 00BADDD3 63
#
Have Steel Greatsword
0
JorgeFFC
0 00BADDD7 63
#
Have Defender
0
JorgeFFC
0 00BADDDB 63
#
Have Defender +1
0
JorgeFFC
0 00BADDDF 63
#
Have Defender +2
0
JorgeFFC
0 00BADDE3 63
#
Have Platinum Greatsword
0
JorgeFFC
0 00BADDE7 63
#
Have Greatsword
0
JorgeFFC
0 00BADDEB 63
#
Have Greatsword +1
0
JorgeFFC
0 00BADDEF 63
#
Have Greatsword +2
0
JorgeFFC
0 00BADDF3 63
#
Have Silver Greatsword
0
JorgeFFC
0 00BADDF7 63
#
Have Golden Greatsword
0
JorgeFFC
0 00BADDFB 63
#
Have Amber Gold Greatsword
0
JorgeFFC
0 00BADDFF 63
#
Have Amber Gold Greatsword +1
0
JorgeFFC
0 00BADE03 63
#
Have Amber Gold Greatsword +2
0
JorgeFFC
0 00BADE07 63
#
Have Amber Gold Greatsword +3
0
JorgeFFC
0 00BADE0B 63
#
Have Dragonsbane Sword
0
JorgeFFC
0 00BADE0F 63
#
Have Zanbatou
0
JorgeFFC
0 00BADE13 63
#
Have Zanbatou +1
0
JorgeFFC
0 00BADE17 63
#
Have Ambition Greatsword
0
JorgeFFC
0 00BADE1F 63
#
Have Elfin Greatsword
0
JorgeFFC
0 00BADE23 63
#
Have Answerer
0
JorgeFFC
0 00BADE27 63
#
Have Answerer +1
0
JorgeFFC
0 00BADE2B 63
#
Have Elfin Greatsword(Error on game?)
0
JorgeFFC
0 00BADE2F 63
#
Have Real Judgment
0
JorgeFFC
0 00BADE33 63
#
Have Judgment +2
0
JorgeFFC
0 00BADE37 63
#
Have Judgment +3
0
JorgeFFC
0 00BADE3B 63
#
Have Laevateinn
0
JorgeFFC
0 00BADE3F 63
#
Have Tanit's Greatsword
0
JorgeFFC
0 00BADE43 63
#
Have Tanit's Greatsword +1
0
JorgeFFC
0 00BADE47 63
#
Have Tanit's Greatsword +2
0
JorgeFFC
0 00BADE4B 63
#
Have Tanit's Greatsword +3
0
JorgeFFC
0 00BADE4F 63
#
Have Tanit's Greatsword +4
0
JorgeFFC
0 00BADE53 63
#
Have Tanit's Greatsword +5
0
JorgeFFC
0 00BADE57 63
#
Have Tanit's Greatsword +6
0
JorgeFFC
0 00BADE5B 63
#
Have Tanit's Fake Sword
0
JorgeFFC
0 00BADE5F 63
#
Have Tanit's Holy Sword
0
JorgeFFC
0 00BADE63 63
#
Have Sword of Nihility
0
JorgeFFC
0 00BADE67 63
#
Have Sword of Nihility +1
0
JorgeFFC
0 00BADE6B 63
#
Have Sword of Nihility +2
0
JorgeFFC
0 00BADE6F 63
#
Have Fencing Blades
0
JorgeFFC
0 00BADE8B 63
#
Have Sharp Blades
0
JorgeFFC
0 00BADE8F 63
#
Have Cutlasses
0
JorgeFFC
0 00BADE93 63
#
Have Cutlasses +1
0
JorgeFFC
0 00BADE97 63
#
Have Cutlasses +2
0
JorgeFFC
0 00BADE9B 63
#
Have Hunting Blades
0
JorgeFFC
0 00BADE9F 63
#
Have Master's Blades
0
JorgeFFC
0 00BADEA3 63
#
Have Tribal Blades
0
JorgeFFC
0 00BADEA7 63
#
Have Tribal Blades +1
0
JorgeFFC
0 00BADEAB 63
#
Have Tribal Blades +2
0
JorgeFFC
0 00BADEAF 63
#
Have Skull Crusher
0
JorgeFFC
0 00BADEB3 63
#
Have Anamnesis Blade
0
JorgeFFC
0 00BADEB7 63
#
Have Cyclone Blades
0
JorgeFFC
0 00BADEBB 63
#
Have Mercenary's Blades
0
JorgeFFC
0 00BADEBF 63
#
Have Mercenary's Blades +1
0
JorgeFFC
0 00BADEC3 63
#
Have Mercenary's Blades +2
0
JorgeFFC
0 00BADEC7 63
#
Have Reaper's Blades
0
JorgeFFC
0 00BADECB 63
#
Have Heartbreaker
0
JorgeFFC
0 00BADECF 63
#
Have Rumble Rush +1
0
JorgeFFC
0 00BADED3 63
#
Have Rumble Rush +2
0
JorgeFFC
0 00BADED7 63
#
Have Giant's Blades
0
JorgeFFC
0 00BADEDB 63
#
Have Team Sieger
0
JorgeFFC
0 00BADEDF 63
#
Have Team Sieger +1
0
JorgeFFC
0 00BADEE3 63
#
Have Rune Scimitars
0
JorgeFFC
0 00BADEE7 63
#
Have Rune Scimitars +1
0
JorgeFFC
0 00BADEEB 63
#
Have Rune Scimitars +2
0
JorgeFFC
0 00BADEEF 63
#
Have Rune Scimitars +3
0
JorgeFFC
0 00BADEF3 63
#
Have Valhalla Blade
0
JorgeFFC
0 00BADEF7 63
#
Have Copper Spear
0
JorgeFFC
0 00BADF13 63
#
Have Brass Spear
0
JorgeFFC
0 00BADF17 63
#
Have Iron Spear
0
JorgeFFC
0 00BADF1B 63
#
Have Iron Spear +1
0
JorgeFFC
0 00BADF1F 63
#
Have Iron Spear +2
0
JorgeFFC
0 00BADF23 63
#
Have Steel Spear
0
JorgeFFC
0 00BADF27 63
#
Have Damascus Spear
0
JorgeFFC
0 00BADF2B 63
#
Have Platinum Spear
0
JorgeFFC
0 00BADF2F 63
#
Have Platinum Spear +1
0
JorgeFFC
0 00BADF33 63
#
Have Platinum Spear +2
0
JorgeFFC
0 00BADF37 63
#
Have Hasta
0
JorgeFFC
0 00BADF3B 63
#
Have Battle Fork
0
JorgeFFC
0 00BADF3F 63
#
Have Elfin Spear
0
JorgeFFC
0 00BADF43 63
#
Have Elfin Spear +1
0
JorgeFFC
0 00BADF47 63
#
Have Elfin Spear +2
0
JorgeFFC
0 00BADF4B 63
#
Have Silver Spear
0
JorgeFFC
0 00BADF4F 63
#
Have Golden Spear
0
JorgeFFC
0 00BADF53 63
#
Have Trident
0
JorgeFFC
0 00BADF57 63
#
Have Trident +1
0
JorgeFFC
0 00BADF5B 63
#
Have Trident +2
0
JorgeFFC
0 00BADF5F 63
#
Have Trident +3
0
JorgeFFC
0 00BADF63 63
#
Have Amber Gold Spear
0
JorgeFFC
0 00BADF67 63
#
Have Pillum Legatos
0
JorgeFFC
0 00BADF6B 63
#
Have Ga-Boi
0
JorgeFFC
0 00BADF6F 63
#
Have Ga-Derg
0
JorgeFFC
0 00BADF73 63
#
Have Rhongomyniad
0
JorgeFFC
0 00BADF77 63
#
Have Apollyon
0
JorgeFFC
0 00BADF7B 63
#
Have Omega Apollyon
0
JorgeFFC
0 00BADF7F 63
#
Have Apollyon +2
0
JorgeFFC
0 00BADF83 63
#
Have Apollyon +3
0
JorgeFFC
0 00BADF87 63
#
Have Gae Bolg
0
JorgeFFC
0 00BADF8B 63
#
Have Reaper's Spear
0
JorgeFFC
0 00BADF8F 63
#
Have Cypher +1
0
JorgeFFC
0 00BADF93 63
#
Have Brionac
0
JorgeFFC
0 00BADF97 63
#
Have Brionac +1
0
JorgeFFC
0 00BADF9B 63
#
Have Plague Spear
0
JorgeFFC
0 00BADF9F 63
#
Have Plague Spear +1
0
JorgeFFC
0 00BADFA3 63
#
Have Pissar
0
JorgeFFC
0 00BADFA7 63
#
Have Pissar +1
0
JorgeFFC
0 00BADFAB 63
#
Have Bronze Hammer
0
JorgeFFC
0 00BADFC7 63
#
Have Platinum Hammer
0
JorgeFFC
0 00BADFCB 63
#
Have Platinum Hammer +1
0
JorgeFFC
0 00BADFCF 63
#
Have Platinum Hammer +2
0
JorgeFFC
0 00BADFD3 63
#
Have Elfin Hammer
0
JorgeFFC
0 00BADFD7 63
#
Have War Hammer
0
JorgeFFC
0 00BADFDB 63
#
Have Silver Hammer
0
JorgeFFC
0 00BADFDF 63
#
Have Stardust Hammer
0
JorgeFFC
0 00BADFE3 63
#
Have Stardust Hammer +1
0
JorgeFFC
0 00BADFE7 63
#
Have Stardust Hammer +2
0
JorgeFFC
0 00BADFEB 63
#
Have Heavy Hammer
0
JorgeFFC
0 00BADFEF 63
#
Have Golden Hammer
0
JorgeFFC
0 00BADFF3 63
#
Have Golden Hammer +1
0
JorgeFFC
0 00BADFF7 63
#
Have Golden Hammer +2
0
JorgeFFC
0 00BADFFB 63
#
Have Cyclone Hammer
0
JorgeFFC
0 00BADFFF 63
#
Have Earthdragon Hammer
0
JorgeFFC
0 00BAE003 63
#
Have Earthdragon Hammer +1
0
JorgeFFC
0 00BAE007 63
#
Have Earthdragon Hammer +2
0
JorgeFFC
0 00BAE00B 63
#
Have Guardian Hammer
0
JorgeFFC
0 00BAE00F 63
#
Have Guardian Hammer +1
0
JorgeFFC
0 00BAE013 63
#
Have Guardian Hammer +2
0
JorgeFFC
0 00BAE017 63
#
Have Gaia Crusher
0
JorgeFFC
0 00BAE01B 63
#
Have Dark Scepter
0
JorgeFFC
0 00BAE01F 63
#
Have Giant's Hammer
0
JorgeFFC
0 00BAE023 63
#
Have One-Ton Hammer
0
JorgeFFC
0 00BAE027 63
#
Have One-Ton Hammer +1
0
JorgeFFC
0 00BAE02B 63
#
Have One-Ton Hammer +2
0
JorgeFFC
0 00BAE02F 63
#
Have One-Ton Hammer +3
0
JorgeFFC
0 00BAE033 63
#
Have Yagrush
0
JorgeFFC
0 00BAE037 63
#
Have Ayamur
0
JorgeFFC
0 00BAE03B 63
#
Have Ayamur Magna
0
JorgeFFC
0 00BAE03F 63
#
Have Massacre Labrys
0
JorgeFFC
0 00BAE043 63
#
Have Lia Fail
0
JorgeFFC
0 00BAE047 63
#
Have Destined Lia Fail
0
JorgeFFC
0 00BAE04B 63
#
Have Lia Fail +2
0
JorgeFFC
0 00BAE04F 63
#
Have Lia Fail +3
0
JorgeFFC
0 00BAE053 63
#
Have Goibniu Hammer
0
JorgeFFC
0 00BAE057 63
#
Have Bone Bow
0
JorgeFFC
0 00BAE073 63
#
Have Short Bow
0
JorgeFFC
0 00BAE077 63
#
Have Hunter's Bow
0
JorgeFFC
0 00BAE07B 63
#
Have Hunter's Bow +1
0
JorgeFFC
0 00BAE07F 63
#
Have Hunter's Bow +2
0
JorgeFFC
0 00BAE083 63
#
Have Strong Bow
0
JorgeFFC
0 00BAE087 63
#
Have Long Bow
0
JorgeFFC
0 00BAE08B 63
#
Have Long Bow +1
0
JorgeFFC
0 00BAE08F 63
#
Have Long Bow +2
0
JorgeFFC
0 00BAE093 63
#
Have Mistletoe Bow
0
JorgeFFC
0 00BAE097 63
#
Have Damascus Bow
0
JorgeFFC
0 00BAE09B 63
#
Have Pterodactyl Bow
0
JorgeFFC
0 00BAE09F 63
#
Have Jet-Black Bow
0
JorgeFFC
0 00BAE0A3 63
#
Have Jet-Black Bow +1
0
JorgeFFC
0 00BAE0A7 63
#
Have Jet-Black Bow +2
0
JorgeFFC
0 00BAE0AB 63
#
Have Jet-Black Bow +3
0
JorgeFFC
0 00BAE0AF 63
#
Have Jet-Black Bow +4
0
JorgeFFC
0 00BAE0B3 63
#
Have Bull's Eye Bow
0
JorgeFFC
0 00BAE0B7 63
#
Have Platinum Bow
0
JorgeFFC
0 00BAE0BB 63
#
Have Elfin Bow
0
JorgeFFC
0 00BAE0BF 63
#
Have Silver Bow
0
JorgeFFC
0 00BAE0C3 63
#
Have Silver Bow +1
0
JorgeFFC
0 00BAE0C7 63
#
Have Silver Bow +2
0
JorgeFFC
0 00BAE0CB 63
#
Have Golden Bow
0
JorgeFFC
0 00BAE0CF 63
#
Have Blue Sky Bow
0
JorgeFFC
0 00BAE0D3 63
#
Have Blue Sky Bow +1
0
JorgeFFC
0 00BAE0D7 63
#
Have Blue Sky Bow +2
0
JorgeFFC
0 00BAE0DB 63
#
Have Sylph's Bow
0
JorgeFFC
0 00BAE0DF 63
#
Have Tempestlord Bow
0
JorgeFFC
0 00BAE0E3 63
#
Have Cernunnos Bow
0
JorgeFFC
0 00BAE0E7 63
#
Have Bow of Aengus
0
JorgeFFC
0 00BAE0EB 63
#
Have Songbow of Aengus
0
JorgeFFC
0 00BAE0EF 63
#
Have Bow of Aengus +2
0
JorgeFFC
0 00BAE0F3 63
#
Have Bow of Esus
0
JorgeFFC
0 00BAE0F7 63
#
Have Astral Al-Nasr
0
JorgeFFC
0 00BAE0FB 63
#
Have Grand Al-Nasr
0
JorgeFFC
0 00BAE0FF 63
#
Have Astral Al-Nasr +2
0
JorgeFFC
0 00BAE103 63
#
Have Astral Al-Nasr +3
0
JorgeFFC
0 00BAE107 63
#
Have Barca Bow
0
JorgeFFC
0 00BAE10B 63
#
Have Birch Staff
0
JorgeFFC
0 00BAE28B 63
#
Have Hazel Staff
0
JorgeFFC
0 00BAE28F 63
#
Have Mistletoe Staff
0
JorgeFFC
0 00BAE293 63
#
Have Mistletoe Staff +1
0
JorgeFFC
0 00BAE297 63
#
Have Mistletoe Staff +2
0
JorgeFFC
0 00BAE29B 63
#
Have Vision Staff
0
JorgeFFC
0 00BAE29F 63
#
Have Elfin Staff
0
JorgeFFC
0 00BAE2A3 63
#
Have Elfin Staff +1
0
JorgeFFC
0 00BAE2A7 63
#
Have Elfin Staff +2
0
JorgeFFC
0 00BAE2AB 63
#
Have Staff of Giants
0
JorgeFFC
0 00BAE2AF 63
#
Have Dragonfang Staff
0
JorgeFFC
0 00BAE2B3 63
#
Have Dragonfang Staff +1
0
JorgeFFC
0 00BAE2B7 63
#
Have Dragonfang Staff +2
0
JorgeFFC
0 00BAE2BB 63
#
Have Dragonfang Staff +3
0
JorgeFFC
0 00BAE2BF 63
#
Have Dragonfang Staff +4
0
JorgeFFC
0 00BAE2C3 63
#
Have Dragonfang Staff +5
0
JorgeFFC
0 00BAE2C7 63
#
Have Sage Staff
0
JorgeFFC
0 00BAE2CB 63
#
Have Sage Staff +1
0
JorgeFFC
0 00BAE2CF 63
#
Have Sage Staff +2
0
JorgeFFC
0 00BAE2D3 63
#
Have Sage Staff +3
0
JorgeFFC
0 00BAE2D7 63
#
Have Sage Staff +4
0
JorgeFFC
0 00BAE2DB 63
#
Have Sage Staff +5
0
JorgeFFC
0 00BAE2DF 63
#
Have Prophet Staff
0
JorgeFFC
0 00BAE2E3 63
#
Have Druidic Staff
0
JorgeFFC
0 00BAE2E7 63
#
Have Staff of Judgment
0
JorgeFFC
0 00BAE2EB 63
#
Have Eternal Spring
0
JorgeFFC
0 00BAE2EF 63
#
Have Staff of Wisdom
0
JorgeFFC
0 00BAE2F3 63
#
Have Underworld Staff
0
JorgeFFC
0 00BAE2F7 63
#
Have Sephirot Staff
0
JorgeFFC
0 00BAE2FB 63
#
Have Profane Sephirot
0
JorgeFFC
0 00BAE2FF 63
#
Have Sephirot Staff +2
0
JorgeFFC
0 00BAE303 63
#
Have Sephirot Staff +3
0
JorgeFFC
0 00BAE307 63
#
Have Dragongod Staff
0
JorgeFFC
0 00BAE30B 63
#
Have Golden Dragongod
0
JorgeFFC
0 00BAE30F 63
#
Have Harlot Staff +2
0
JorgeFFC
0 00BAE313 63
#
Have Harlot Staff +3
0
JorgeFFC
0 00BAE317 63
#
Have Caduceus
0
JorgeFFC
0 00BAE31B 63
#
Have Heretic Staff
0
JorgeFFC
0 00BAE31F 63
#
Have Heaven Corona
0
JorgeFFC
0 00BAE323 63
#
Have Emperor Staff
0
JorgeFFC
0 00BAE327 63
#
Have Elegy Flute
0
JorgeFFC
0 00BAE32B 63
#
Have Tome of Converts
0
JorgeFFC
0 00BAE343 63
#
Have Elfin Diary
0
JorgeFFC
0 00BAE347 63
#
Have Tome of Lismore
0
JorgeFFC
0 00BAE34B 63
#
Have Tome of Imlaw
0
JorgeFFC
0 00BAE34F 63
#
Have Tome of Ocheri
0
JorgeFFC
0 00BAE353 63
#
Have Tome of Giants
0
JorgeFFC
0 00BAE357 63
#
Have Tome of Tohomach
0
JorgeFFC
0 00BAE35B 63
#
Have Tome of Tohomach +1
0
JorgeFFC
0 00BAE35F 63
#
Have Tome of Dea
0
JorgeFFC
0 00BAE363 63
#
Have Tome of Ephetra
0
JorgeFFC
0 00BAE367 63
#
Have Tome of Ephetra +1
0
JorgeFFC
0 00BAE36B 63
#
Have Book of Taliesin
0
JorgeFFC
0 00BAE36F 63
#
Have Tome of Togal
0
JorgeFFC
0 00BAE373 63
#
Have Togal Testament
0
JorgeFFC
0 00BAE377 63
#
Have Book of Mago
0
JorgeFFC
0 00BAE37B 63
#
Have Vitruvius
0
JorgeFFC
0 00BAE37F 63
#
Have Throwing Dagger
0
JorgeFFC
0 00BAE123 63
#
Have Slayer
0
JorgeFFC
0 00BAE127 63
#
Have Slayer +1
0
JorgeFFC
0 00BAE12B 63
#
Have Slayer +2
0
JorgeFFC
0 00BAE12F 63
#
Have Stilleto
0
JorgeFFC
0 00BAE133 63
#
Have Misericorde
0
JorgeFFC
0 00BAE137 63
#
Have Mercenary Knife
0
JorgeFFC
0 00BAE13B 63
#
Have Mercenary Knife +1
0
JorgeFFC
0 00BAE13F 63
#
Have Mercenary Knife +2
0
JorgeFFC
0 00BAE143 63
#
Have Elfin Knife
0
JorgeFFC
0 00BAE147 63
#
Have Flying Fan
0
JorgeFFC
0 00BAE14B 63
#
Have Spartan Knife
0
JorgeFFC
0 00BAE14F 63
#
Have Spartan Knife +1
0
JorgeFFC
0 00BAE153 63
#
Have Spartan Knife +2
0
JorgeFFC
0 00BAE157 63
#
Have Spartan Knife +3
0
JorgeFFC
0 00BAE15B 63
#
Have Death Marker
0
JorgeFFC
0 00BAE15F 63
#
Have Shadowcutter
0
JorgeFFC
0 00BAE163 63
#
Have Dragon Edge
0
JorgeFFC
0 00BAE167 63
#
Have Dragon Edge +1
0
JorgeFFC
0 00BAE16B 63
#
Have Dragon Edge +2
0
JorgeFFC
0 00BAE16F 63
#
Have Rose Thron
0
JorgeFFC
0 00BAE173 63
#
Have Sidewinder
0
JorgeFFC
0 00BAE177 63
#
Have Sidewinder +1
0
JorgeFFC
0 00BAE17B 63
#
Have Nightmare
0
JorgeFFC
0 00BAE17F 63
#
Have Deep Nightmare
0
JorgeFFC
0 00BAE183 63
#
Have Nightmare +2
0
JorgeFFC
0 00BAE187 63
#
Have Crimson Rose
0
JorgeFFC
0 00BAE18B 63
#
Have Photon Blade
0
JorgeFFC
0 00BAE18F 63
#
Have Radical Fangs
0
JorgeFFC
0 00BAE1AB 63
#
Have Weak Fang
0
JorgeFFC
0 00BAE1AF 63
#
Have Normal Fang
0
JorgeFFC
0 00BAE1B3 63
#
Have Good Fang
0
JorgeFFC
0 00BAE1B7 63
#
Have Great Fang
0
JorgeFFC
0 00BAE1BB 63
#
Have Strong Fang
0
JorgeFFC
0 00BAE1BF 63
#
Have Strong Fang +1
0
JorgeFFC
0 00BAE1C3 63
#
Have Sturdy Fang
0
JorgeFFC
0 00BAE1C7 63
#
Have Sturdy Fang +1
0
JorgeFFC
0 00BAE1CB 63
#
Have Sturdy Fang +2
0
JorgeFFC
0 00BAE1CF 63
#
Have Mammoth's Tusk
0
JorgeFFC
0 00BAE1D3 63
#
Have Monstrous Fang
0
JorgeFFC
0 00BAE1D7 63
#
Have War God Fang
0
JorgeFFC
0 00BAE1DB 63
#
Have Holy God Fang
0
JorgeFFC
0 00BAE1DF 63
#
Have Cursed Fang
0
JorgeFFC
0 00BAE1E3 63
#
Have Cursed Fang +1
0
JorgeFFC
0 00BAE1E7 63
#
Have Splendid Fang
0
JorgeFFC
0 00BAE1EB 63
#
Have Splendid Fang +1
0
JorgeFFC
0 00BAE1EF 63
#
Have Cerberus Fang
0
JorgeFFC
0 00BAE1F3 63
#
Have Crom Cruach Fang
0
JorgeFFC
0 00BAE1F7 63
#
Have God-Beast Fang
0
JorgeFFC
0 00BAE1FB 63
#
Have Hammer Hand
0
JorgeFFC
0 00BAE217 63
#
Have Hammer Knuckle
0
JorgeFFC
0 00BAE21B 63
#
Have Knuckle Duster
0
JorgeFFC
0 00BAE21F 63
#
Have Magical Hand
0
JorgeFFC
0 00BAE223 63
#
Have Magical Hand +1
0
JorgeFFC
0 00BAE227 63
#
Have Drill Punch
0
JorgeFFC
0 00BAE22B 63
#
Have Drill Punch +1
0
JorgeFFC
0 00BAE22F 63
#
Have Boost Knuckle
0
JorgeFFC
0 00BAE233 63
#
Have Boost Knuckle +1
0
JorgeFFC
0 00BAE237 63
#
Have Boost Knuckle +2
0
JorgeFFC
0 00BAE23B 63
#
Have Death Hand
0
JorgeFFC
0 00BAE23F 63
#
Have Titan Hand
0
JorgeFFC
0 00BAE243 63
#
Have Spartan Knuckle
0
JorgeFFC
0 00BAE247 63
#
Have Kaiser Knuckle
0
JorgeFFC
0 00BAE24B 63
#
Have Kaiser Knuckle M
0
JorgeFFC
0 00BAE24F 63
#
Have Kaiser Knuckle A
0
JorgeFFC
0 00BAE253 63
#
Have Miracle Drill
0
JorgeFFC
0 00BAE257 63
#
Have Miracle Drill +1
0
JorgeFFC
0 00BAE25B 63
#
Have Diabolos
0
JorgeFFC
0 00BAE25F 63
#
Have Atlas Fist
0
JorgeFFC
0 00BAE263 63
#
Have Atlas Fist +1
0
JorgeFFC
0 00BAE267 63
#
Have Great Crusher
0
JorgeFFC
0 00BAE26B 63
#
Have Atlas Crusher
0
JorgeFFC
0 00BAE26F 63
#
Have Straw Hat
0
JorgeFFC
0 00BAE46B 63
#
Have Feathered Hat
0
JorgeFFC
0 00BAE46F 63
#
Have Black Hood
0
JorgeFFC
0 00BAE473 63
#
Have Wizard's Hat
0
JorgeFFC
0 00BAE477 63
#
Have Fancy Katyusha
0
JorgeFFC
0 00BAE47B 63
#
Have Tiara
0
JorgeFFC
0 00BAE47F 63
#
Have Crown of Thorns
0
JorgeFFC
0 00BAE483 63
#
Have Primula Circlet
0
JorgeFFC
0 00BAE487 63
#
Have Twilight Crown
0
JorgeFFC
0 00BAE48B 63
#
Have Muses' Crown
0
JorgeFFC
0 00BAE48F 63
#
Have Fluid Headgear
0
JorgeFFC
0 00BAE493 63
#
Have Godess Ribbon
0
JorgeFFC
0 00BAE497 63
#
Have Copper Helmet
0
JorgeFFC
0 00BAE4AF 63
#
Have Iron Helmet
0
JorgeFFC
0 00BAE4B3 63
#
Have Steel Helmet
0
JorgeFFC
0 00BAE4B7 63
#
Have Elfin Helmet
0
JorgeFFC
0 00BAE4BB 63
#
Have Golden Helmet
0
JorgeFFC
0 00BAE4BF 63
#
Have Amber Gold Helmet
0
JorgeFFC
0 00BAE4C3 63
#
Have War Elf's Crown
0
JorgeFFC
0 00BAE4C7 63
#
Have Gladiator's Galea
0
JorgeFFC
0 00BAE4CB 63
#
Have Spirit Helmet
0
JorgeFFC
0 00BAE4CF 63
#
Have Harbinger Helmet
0
JorgeFFC
0 00BAE4D3 63
#
Have Helm of Light
0
JorgeFFC
0 00BAE4D7 63
#
Have Linen Robe
0
JorgeFFC
0 00BAE4EF 63
#
Have Cotton Robe
0
JorgeFFC
0 00BAE4F3 63
#
Have Robe of Sages
0
JorgeFFC
0 00BAE4F7 63
#
Have Calm Robe
0
JorgeFFC
0 00BAE4FB 63
#
Have Gorgeous Dress
0
JorgeFFC
0 00BAE4FF 63
#
Have Silk Dress
0
JorgeFFC
0 00BAE503 63
#
Have Black Clothes
0
JorgeFFC
0 00BAE507 63
#
Have Swordsman's Coat
0
JorgeFFC
0 00BAE50B 63
#
Have Elfin Robe
0
JorgeFFC
0 00BAE50F 63
#
Have Robe of Stars
0
JorgeFFC
0 00BAE513 63
#
Have Maid's Appron
0
JorgeFFC
0 00BAE517 63
#
Have Gown of Rule
0
JorgeFFC
0 00BAE51B 63
#
Have Chameleon Robe
0
JorgeFFC
0 00BAE51F 63
#
Have Bloodstained Dress
0
JorgeFFC
0 00BAE523 63
#
Have Robe of Life
0
JorgeFFC
0 00BAE527 63
#
Have Diabolical Cloak
0
JorgeFFC
0 00BAE52B 63
#
Have Spprigan Vest
0
JorgeFFC
0 00BAE52F 63
#
Have Archwizard Robe
0
JorgeFFC
0 00BAE533 63
#
Have Agony Mantle
0
JorgeFFC
0 00BAE537 63
#
Have Cloth Armor
0
JorgeFFC
0 00BAE54B 63
#
Have Chainmail
0
JorgeFFC
0 00BAE54F 63
#
Have Steel Chainamil
0
JorgeFFC
0 00BAE553 63
#
Have Platinum Chainmail
0
JorgeFFC
0 00BAE557 63
#
Have Lorica Hamata
0
JorgeFFC
0 00BAE55B 63
#
Have Silver Chainmail
0
JorgeFFC
0 00BAE55F 63
#
Have Golden Chainmail
0
JorgeFFC
0 00BAE563 63
#
Have Amber Gold Chainmail
0
JorgeFFC
0 00BAE567 63
#
Have Lorica Squamata
0
JorgeFFC
0 00BAE56B 63
#
Have Brave Mail
0
JorgeFFC
0 00BAE56F 63
#
Have Mirage Vest
0
JorgeFFC
0 00BAE573 63
#
Have Samiel Doublet
0
JorgeFFC
0 00BAE577 63
#
Have Shirt of Goibniu
0
JorgeFFC
0 00BAE57B 63
#
Have Shroud of Light
0
JorgeFFC
0 00BAE57F 63
#
Have Leather Armor
0
JorgeFFC
0 00BAE593 63
#
Have Bronze Armor
0
JorgeFFC
0 00BAE597 63
#
Have Brass Armor
0
JorgeFFC
0 00BAE59B 63
#
Have Iron Armor
0
JorgeFFC
0 00BAE59F 63
#
Have Steel Armor
0
JorgeFFC
0 00BAE5A3 63
#
Have Damascus Armor
0
JorgeFFC
0 00BAE5A7 63
#
Have Platinum Armor
0
JorgeFFC
0 00BAE5AB 63
#
Have Segmentata
0
JorgeFFC
0 00BAE5AF 63
#
Have Elfin Armor
0
JorgeFFC
0 00BAE5B3 63
#
Have Silver Armor
0
JorgeFFC
0 00BAE5B7 63
#
Have Golden Armor
0
JorgeFFC
0 00BAE5BB 63
#
Have Amber Gold Armor
0
JorgeFFC
0 00BAE5BF 63
#
Have Valiant
0
JorgeFFC
0 00BAE5C3 63
#
Have Relic Armor
0
JorgeFFC
0 00BAE5C7 63
#
Have Macha's Armor
0
JorgeFFC
0 00BAE5CB 63
#
Have Esus's Armor
0
JorgeFFC
0 00BAE5CF 63
#
Have Black Armor
0
JorgeFFC
0 00BAE5D3 63
#
Have Light Armor
0
JorgeFFC
0 00BAE5D7 63
#
Have Spirit Armor
0
JorgeFFC
0 00BAE5DB 63
#
Have Miraculous Armor
0
JorgeFFC
0 00BAE5DF 63
#
Have Chainmail Glove
0
JorgeFFC
0 00BAE5F3 63
#
Have Bronze Gauntlet
0
JorgeFFC
0 00BAE5F7 63
#
Have Steel Gauntlet
0
JorgeFFC
0 00BAE5FB 63
#
Have Elfin Gauntlet
0
JorgeFFC
0 00BAE5FF 63
#
Have Titan Gauntlet
0
JorgeFFC
0 00BAE603 63
#
Have Dragon Gauntlet
0
JorgeFFC
0 00BAE607 63
#
Have Amber Gold Gauntlet
0
JorgeFFC
0 00BAE60B 63
#
Have Glacier Gauntlet
0
JorgeFFC
0 00BAE60F 63
#
Have Manhunt Gauntlet
0
JorgeFFC
0 00BAE613 63
#
Have Cursed Gauntlet
0
JorgeFFC
0 00BAE617 63
#
Have Holy Gauntlet
0
JorgeFFC
0 00BAE61B 63
#
Have Earth Gauntlet
0
JorgeFFC
0 00BAE61F 63
#
Have Timber Bracelet
0
JorgeFFC
0 00BAE633 63
#
Have Launch Bracelet
0
JorgeFFC
0 00BAE637 63
#
Have Gaudy Bracelet
0
JorgeFFC
0 00BAE63B 63
#
Have Warrior Bracelet
0
JorgeFFC
0 00BAE63F 63
#
Have Heroic Bracelet
0
JorgeFFC
0 00BAE643 63
#
Have Shooter's Bracelet
0
JorgeFFC
0 00BAE647 63
#
Have Mage's Bracelet
0
JorgeFFC
0 00BAE64B 63
#
Have Exorcits Bracelet
0
JorgeFFC
0 00BAE64F 63
#
Have Thief's Bracelet
0
JorgeFFC
0 00BAE653 63
#
Have Comet Bracelet
0
JorgeFFC
0 00BAE657 63
#
Have Demonic Bracelet
0
JorgeFFC
0 00BAE65B 63
#
Have Master's Bracelet
0
JorgeFFC
0 00BAE65F 63
#
Have Draconic Mitts
0
JorgeFFC
0 00BAE663 63
#
Have Draupnir
0
JorgeFFC
0 00BAE667 63
#
Have Red Steel Band
0
JorgeFFC
0 00BAE66B 63
#
Have Antimagic Bracelet
0
JorgeFFC
0 00BAE66F 63
#
Have Quartz Ring
0
JorgeFFC
0 00BAE683 63
#
Have Fluorite RIng
0
JorgeFFC
0 00BAE687 63
#
Have Pearl Ring
0
JorgeFFC
0 00BAE68B 63
#
Have Iris Ring
0
JorgeFFC
0 00BAE68F 63
#
Have Crystalline Ring
0
JorgeFFC
0 00BAE693 63
#
Have Steadfast Ring
0
JorgeFFC
0 00BAE697 63
#
Have Emerald Ring
0
JorgeFFC
0 00BAE69B 63
#
Have Black Pearl Ring
0
JorgeFFC
0 00BAE69F 63
#
Have Calaina Ring
0
JorgeFFC
0 00BAE6A3 63
#
Have Irisest Ring
0
JorgeFFC
0 00BAE6A7 63
#
Have Aventurine Ring
0
JorgeFFC
0 00BAE6AB 63
#
Have Ultraviolet Ring
0
JorgeFFC
0 00BAE6AF 63
#
Have Hale Ring
0
JorgeFFC
0 00BAE6B3 63
#
Have Ruby Ring
0
JorgeFFC
0 00BAE6B7 63
#
Have Coral Ring
0
JorgeFFC
0 00BAE6BB 63
#
Have Topaz Ring
0
JorgeFFC
0 00BAE6BF 63
#
Have Cheraunia Ring
0
JorgeFFC
0 00BAE6C3 63
#
Have Asterio Ring
0
JorgeFFC
0 00BAE6C7 63
#
Have Selenite Ring
0
JorgeFFC
0 00BAE6CB 63
#
Have Perseus Ring
0
JorgeFFC
0 00BAE6CF 63
#
Have Amber Ring
0
JorgeFFC
0 00BAE6D3 63
#
Have Opal Ring
0
JorgeFFC
0 00BAE6D7 63
#
Have Asteria Ring
0
JorgeFFC
0 00BAE6DB 63
#
Have Adamas Ring
0
JorgeFFC
0 00BAE6DF 63
#
Have Standard Ring
0
JorgeFFC
0 00BAE6E3 63
#
Have Element Ring
0
JorgeFFC
0 00BAE6E7 63
#
Have Ascetic Ring
0
JorgeFFC
0 00BAE6EB 63
#
Have Deadman's Ring
0
JorgeFFC
0 00BAE6EF 63
#
Have Guru's Ring
0
JorgeFFC
0 00BAE6F3 63
#
Have Golem's Eye
0
JorgeFFC
0 00BAE6F7 63
#
Have Tribal Torc
0
JorgeFFC
0 00BAE70F 63
#
Have Slave Torc
0
JorgeFFC
0 00BAE713 63
#
Have Smith Torc
0
JorgeFFC
0 00BAE717 63
#
Have Thief Torc
0
JorgeFFC
0 00BAE71B 63
#
Have Storyteller Torc
0
JorgeFFC
0 00BAE71F 63
#
Have Hermit Torc
0
JorgeFFC
0 00BAE723 63
#
Have Golem Torc
0
JorgeFFC
0 00BAE727 63
#
Have Manipulator Torc
0
JorgeFFC
0 00BAE72B 63
#
Have Torc of Life
0
JorgeFFC
0 00BAE72F 63
#
Have Sequoia Torc
0
JorgeFFC
0 00BAE733 63
#
Have Bird Torc
0
JorgeFFC
0 00BAE737 63
#
Have Puppet Torc
0
JorgeFFC
0 00BAE73B 63
#
Have Hand-knitted Scarf
0
JorgeFFC
0 00BAE73F 63
#
Have Miraculous Torc
0
JorgeFFC
0 00BAE743 63
#
Have Squid Ring
0
JorgeFFC
0 00BAE747 63
#
Have Hunting God's Torc
0
JorgeFFC
0 00BAE74B 63
#
Have Holy Torc
0
JorgeFFC
0 00BAE74F 63
#
Have Crab God's Torc
0
JorgeFFC
0 00BAE753 63
#
Have Torc of Ruler
0
JorgeFFC
0 00BAE757 63
#
Have Dark God's Mask
0
JorgeFFC
0 00BAE75B 63
#
Have Worn-Out Socks
0
JorgeFFC
0 00BAE773 63
#
Have Slippers
0
JorgeFFC
0 00BAE777 63
#
Have Sandals
0
JorgeFFC
0 00BAE77B 63
#
Have Wellies
0
JorgeFFC
0 00BAE77F 63
#
Have Imperial Sandals
0
JorgeFFC
0 00BAE783 63
#
Have Boots
0
JorgeFFC
0 00BAE787 63
#
Have Footguards
0
JorgeFFC
0 00BAE78B 63
#
Have Red Shoes
0
JorgeFFC
0 00BAE78F 63
#
Have Jagdlegg
0
JorgeFFC
0 00BAE793 63
#
Have Thief Shoes
0
JorgeFFC
0 00BAE797 63
#
Have Godspeed Boots
0
JorgeFFC
0 00BAE79B 63
#
Have Fancy Knit Socks
0
JorgeFFC
0 00BAE79F 63
#
Have Soaring Feet
0
JorgeFFC
0 00BAE7A3 63
#
Have Spiked Shoes
0
JorgeFFC
0 00BAE7A7 63
#
Have Fine Boots
0
JorgeFFC
0 00BAE7AB 63
#
Have Iron Geta
0
JorgeFFC
0 00BAE7AF 63
#
Have Safety Shoes
0
JorgeFFC
0 00BAE7B3 63
#
Have Chakra Sandals
0
JorgeFFC
0 00BAE7B7 63
#
Have Sandals of Light
0
JorgeFFC
0 00BAE7BB 63
#
AoB Infinite MP
0
games24.blog.fc2.com/blog-entry-211.html
B 00010000 04000000
B 7CBF28102C0500004180000860BE0000 600000002C0500004180000860BE0000
#
AoB Always Turn 1
0
games24.blog.fc2.com/blog-entry-211.html
B 00010000 04000000
B 30840001B08300703C80000B30630050 30840000B08300703C80000B30630050
#
AoB 999 Skill Points On gain
0
Friend of a Friend
B 00010000 04000000
B 2C0300644081000838600064 386003E7386003E7386003E7
#
AoB 99 Items On Gain
0
Friend of a Friend
B 00010000 04000000
B 2C0300634081000C38600063 386000633860006338600063
#
AoB All Allies And Enemies On Field Are Set To Level 999
0
Friend of a Friend
B 00010000 04000000
B 2C1F0063408100083BE00063 3BE003E73BE003E73BE003E7
#