Homer Lives
0
crapulecorp
0 3505EF99 64
#
Homer Health
0
crapulecorp
0 3505F0DB 28
#
Homer Invincible
0
crapulecorp
0 3505F0DB 28
0 3505F0FE 01
#
Homer Weapon Modifier
0
crapulecorp
0 3505F100 Z
[Z]06=Broom;07=Hammer;08=Catapult[/Z]
#
Marge Lives
0
crapulecorp
0 3505EF91 64
#
Marge Health
0
crapulecorp
0 3505F01B 28
#
Marge Invincible
0
crapulecorp
0 3505F01B 28
0 3505F03E 01
#
Marge Weapon Modifier
0
crapulecorp
0 3505F040 Z
[Z]00=Vacuum;06=Broom;07=Hammer;08=Catapult[/Z]
#
Bart Lives
0
crapulecorp
0 3505EF99 64
#
Bart Health
0
crapulecorp
0 3505F19B 28
#
Bart Invincible
0
crapulecorp
0 3505F19B 28
0 3505F1BE 01
#
Bart Weapon Modifier
0
crapulecorp
0 3505F1C0 Z
[Z]00=Skateboard;06=Broom;07=Hammer;08=Catapult[/Z]
#
Lisa Lives
0
crapulecorp
0 3505EFA9 64
#
Lisa Health
0
crapulecorp
0 3505F25B 28
#
Lisa Invincible
0
crapulecorp
0 3505F25B 28
0 3505F27E 01
#
Lisa Weapon Modifier
0
crapulecorp
0 3505F280 Z
[Z]00=Jump Rope;06=Broom;07=Hammer;08=Catapult[/Z]
#