Memory Infinite Lives (New Order Mode)
0
jgduff1
0 004107CE 05
#
ASM Infinite Lives (New Order Mode)
0
jgduff1
0 000B3ED4 30C60000
#
Memory Infinite Bombs (New Order Mode)
0
jgduff1
0 004107D5 03
#
ASM Infinite Bombs (New Order Mode)
0
jgduff1
0 0001A8FC 30630000
#
Memory Infinite Credits (New Order Mode)
0
jgduff1
0 00312CB7 02
#
ASM Infinite Credits (New Order Mode)
0
jgduff1
0 000116B4 30630000
#
Memory Max Score (New Order Mode)
0
jgduff1
0 004107C8 0000138C
#
ASM Max Score (New Order Mode)
0
jgduff1
0 0001CCFC 90A30008
#